tunnel: 6bf8a022-235d-43c3-a343-c4ebbf888b79
credentials-file: /run/user/1000/geburtstagsquiz-tunnel/6bf8a022-235d-43c3-a343-c4ebbf888b79.json

ingress:
  - hostname: api.disaai.de
    service: http://localhost:3001
    originRequest:
      noTLSVerify: true

  - hostname: tv.disaai.de
    service: http://localhost:5175
    originRequest:
      noTLSVerify: true

  - hostname: host.disaai.de
    service: http://localhost:5173
    originRequest:
      noTLSVerify: true

  - hostname: play.disaai.de
    service: http://localhost:5174
    originRequest:
      noTLSVerify: true

  - service: http_status:404
