import { QuestionType, type Quiz } from "@quiz/shared-types";

const MILLENNIALS_QUIZ: Quiz = {
  id: "millennials-quiz-001",
  title: "Millennials-Quiz",
  questions: [
    // Harry Potter
    {
      id: "q-hp-01",
      type: QuestionType.MultipleChoice,
      text: "Wie lautet das erste Gryffindor-Passwort im ersten Harry-Potter-Film?",
      options: [
        { id: "A", label: "Caput Draconis" },
        { id: "B", label: "Wingardium Leviosa" },
        { id: "C", label: "Lumos Solem" },
        { id: "D", label: "Ohrenschmalz" },
      ],
      correctOptionId: "A",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-hp-02",
      type: QuestionType.MultipleChoice,
      text: "Welches Koerperteil bricht Harry sich beim Quidditch-Spiel in 'Die Kammer des Schreckens', bevor Lockhart hilft?",
      options: [
        { id: "A", label: "Den linken Arm" },
        { id: "B", label: "Den rechten Arm" },
        { id: "C", label: "Das Schluesselbein" },
        { id: "D", label: "Das Handgelenk" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-hp-03",
      type: QuestionType.MultipleChoice,
      text: "Welchen Drachen bekommt Harry in der ersten Aufgabe des Trimagischen Turniers?",
      options: [
        { id: "A", label: "Den chinesischen Feuerball" },
        { id: "B", label: "Den walisischen Gruenschwanz" },
        { id: "C", label: "Den schwedischen Kurzschnauzer" },
        { id: "D", label: "Den ungarischen Hornschwanz" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-hp-04",
      type: QuestionType.MultipleChoice,
      text: "Wie heisst das Magazin, das Xenophilius Lovegood herausgibt?",
      options: [
        { id: "A", label: "Der Klitterer" },
        { id: "B", label: "Der Tagesprophet" },
        { id: "C", label: "Hexenwoche" },
        { id: "D", label: "Der Abendprophet" },
      ],
      correctOptionId: "A",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-hp-05",
      type: QuestionType.MultipleChoice,
      text: "Welches Tier erscheint patronusfoermig bei Snapes Nachricht an Harry im Wald?",
      options: [
        { id: "A", label: "Ein Hirsch" },
        { id: "B", label: "Eine Hirschkuh" },
        { id: "C", label: "Ein Otter" },
        { id: "D", label: "Ein Wolf" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-hp-06",
      type: QuestionType.MultipleChoice,
      text: "Wie heisst der Zauberspruch, mit dem Harry Draco im sechsten Film schwer verletzt?",
      options: [
        { id: "A", label: "Crucio" },
        { id: "B", label: "Expelliarmus" },
        { id: "C", label: "Sectumsempra" },
        { id: "D", label: "Avada Kedavra" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    // Millennial-Slang & Internet-Fossilien
    {
      id: "q-sl-01",
      type: QuestionType.MultipleChoice,
      text: "Welches Geraeusch machte ICQ bei einer neuen Nachricht?",
      options: [
        { id: "A", label: "Ein Ping" },
        { id: "B", label: "Ein Gloeckchen" },
        { id: "C", label: "Uh-oh!" },
        { id: "D", label: "Ein Klopfen" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sl-02",
      type: QuestionType.MultipleChoice,
      text: "Welches deutsche soziale Netzwerk war fuer Schueler praegenster Treffpunkt vor Facebook?",
      options: [
        { id: "A", label: "MySpace" },
        { id: "B", label: "Xing" },
        { id: "C", label: "Studi17" },
        { id: "D", label: "SchuelerVZ" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sl-03",
      type: QuestionType.MultipleChoice,
      text: "Was war 'gruscheln' bei StudiVZ?",
      options: [
        { id: "A", label: "Eine Funktion zum Teilen von Fotos" },
        { id: "B", label: "Ein Spiel im Netzwerk" },
        { id: "C", label: "Das Schreiben oeffentlicher Pinnwand-Posts" },
        { id: "D", label: "Mischung aus gruessen und kuscheln - digitaler Fremdschamkontakt" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sl-04",
      type: QuestionType.MultipleChoice,
      text: "Welche Schriftart galt in Kettenbriefen und peinlichen Profilen als Pflicht-Klischee?",
      options: [
        { id: "A", label: "Arial" },
        { id: "B", label: "Comic Sans" },
        { id: "C", label: "Papyrus" },
        { id: "D", label: "Times New Roman" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sl-05",
      type: QuestionType.MultipleChoice,
      text: "Was war mit 'ASL?' in alten Chats gemeint?",
      options: [
        { id: "A", label: "Account, Status, Link" },
        { id: "B", label: "Age, Sex, Location" },
        { id: "C", label: "Always Stay Logged-in" },
        { id: "D", label: "Assigned Screen Language" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    // 90er/00er Trash-TV
    {
      id: "q-tv-01",
      type: QuestionType.MultipleChoice,
      text: "Wie hiess das deutsche Dschungelcamp offiziell?",
      options: [
        { id: "A", label: "Ueberleben im Dschungel" },
        { id: "B", label: "Dschungel der Stars" },
        { id: "C", label: "Wild und Promi" },
        { id: "D", label: "Ich bin ein Star - Holt mich hier raus!" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-tv-02",
      type: QuestionType.MultipleChoice,
      text: "Wie hiess das Jamba-Frosch-Maskottchen mit dem unvergesslichen Klingelton-Song?",
      options: [
        { id: "A", label: "Crazy Frog" },
        { id: "B", label: "Happy Toad" },
        { id: "C", label: "Ringy" },
        { id: "D", label: "Frogster" },
      ],
      correctOptionId: "A",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-tv-03",
      type: QuestionType.MultipleChoice,
      text: "Wie hiess der Jamba-/Jamster-Hase hinter dem beruechtigten Kuschel Song?",
      options: [
        { id: "A", label: "Sweety" },
        { id: "B", label: "Baby Vuvu" },
        { id: "C", label: "Schnuffel" },
        { id: "D", label: "Husky" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-tv-04",
      type: QuestionType.MultipleChoice,
      text: "Welche legendaere Werbung praegt den Spruch 'Isch abe gar keine Auto'?",
      options: [
        { id: "A", label: "Die Carglass-Werbung" },
        { id: "B", label: "Eine Renault-Clio-Werbung" },
        { id: "C", label: "Die Nescafe-Cappuccino-Werbung mit Angelo" },
        { id: "D", label: "Die Seitenbacher-Werbung" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    // Gaming
    {
      id: "q-gm-01",
      type: QuestionType.MultipleChoice,
      text: "Welcher Gegenstand ruiniert in Mario Kart gezielt den Erstplatzierten?",
      options: [
        { id: "A", label: "Der rote Panzer" },
        { id: "B", label: "Der Blitz" },
        { id: "C", label: "Der Stern" },
        { id: "D", label: "Der blaue Panzer" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-gm-02",
      type: QuestionType.MultipleChoice,
      text: "Was passierte in 'Die Sims', wenn man die Poolleiter entfernte?",
      options: [
        { id: "A", label: "Der Sim wurde unsichtbar" },
        { id: "B", label: "Der Sim konnte ertrinken" },
        { id: "C", label: "Das Spiel stuerzte ab" },
        { id: "D", label: "Der Sim teleportierte sich" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-gm-03",
      type: QuestionType.MultipleChoice,
      text: "Was war der groesste psychologische Terror beim Tamagotchi?",
      options: [
        { id: "A", label: "Es konnte nicht pausiert werden" },
        { id: "B", label: "Das Display war zu klein" },
        { id: "C", label: "Es konnte sterben, wenn man es vernachlaessigte" },
        { id: "D", label: "Die Batterien waren nach zwei Tagen leer" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-gm-04",
      type: QuestionType.MultipleChoice,
      text: "Welches Spiel ist fuer den Satz 'Finish him!' bekannt?",
      options: [
        { id: "A", label: "Street Fighter" },
        { id: "B", label: "Tekken" },
        { id: "C", label: "Mortal Kombat" },
        { id: "D", label: "Soul Calibur" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-gm-05",
      type: QuestionType.MultipleChoice,
      text: "Welche Figur aus 'The Legend of Zelda' ist trotz der Verwirrung gar nicht Zelda?",
      options: [
        { id: "A", label: "Ganon" },
        { id: "B", label: "Impa" },
        { id: "C", label: "Link" },
        { id: "D", label: "Epona" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    // Musik
    {
      id: "q-mu-01",
      type: QuestionType.MultipleChoice,
      text: "Welche Band machte 'Durch den Monsun' 2005 in Deutschland zum Hit?",
      options: [
        { id: "A", label: "Tokio Hotel" },
        { id: "B", label: "My Chemical Romance" },
        { id: "C", label: "Scooter" },
        { id: "D", label: "Silbermond" },
      ],
      correctOptionId: "A",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-mu-02",
      type: QuestionType.MultipleChoice,
      text: "Welche Band veroeffentlichte 'Welcome to the Black Parade'?",
      options: [
        { id: "A", label: "Fall Out Boy" },
        { id: "B", label: "Panic! at the Disco" },
        { id: "C", label: "My Chemical Romance" },
        { id: "D", label: "Simple Plan" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-mu-03",
      type: QuestionType.MultipleChoice,
      text: "Welches Originalstueck hat Crazy Frog 2005 mit seiner Nervensaege-Version verewigt?",
      options: [
        { id: "A", label: "Blue (Da Ba Dee)" },
        { id: "B", label: "Axel F" },
        { id: "C", label: "Sandstorm" },
        { id: "D", label: "Popcorn" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-mu-04",
      type: QuestionType.MultipleChoice,
      text: "Wer hatte den 2000er-Hit 'Dragostea Din Tei' (aka Numa-Numa-Song)?",
      options: [
        { id: "A", label: "Eiffel 65" },
        { id: "B", label: "Basshunter" },
        { id: "C", label: "O-Zone" },
        { id: "D", label: "t.A.T.u." },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-mu-05",
      type: QuestionType.MultipleChoice,
      text: "Welche Gruppe ist fuer 'Blue (Da Ba Dee)' bekannt?",
      options: [
        { id: "A", label: "Aqua" },
        { id: "B", label: "Eiffel 65" },
        { id: "C", label: "Vengaboys" },
        { id: "D", label: "Cascada" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    // Adulting Fails
    {
      id: "q-ad-01",
      type: QuestionType.MultipleChoice,
      text: "Was passiert typischerweise, wenn man rote und weisse Waesche zusammen waescht?",
      options: [
        { id: "A", label: "Gar nichts, ist ein Mythos" },
        { id: "B", label: "Die rote Farbe verblasst" },
        { id: "C", label: "Die Waesche wird steif" },
        { id: "D", label: "Alles wird rosa - Verfaerbungsrisiko" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-ad-02",
      type: QuestionType.MultipleChoice,
      text: "Was macht man mit einem Fettbrand auf dem Herd auf keinen Fall?",
      options: [
        { id: "A", label: "Deckel drauflegen" },
        { id: "B", label: "Mit Wasser loeschen" },
        { id: "C", label: "Herd ausschalten" },
        { id: "D", label: "Feuerloescher benutzen" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-ad-03",
      type: QuestionType.MultipleChoice,
      text: "Was bedeutet MHD auf Lebensmitteln?",
      options: [
        { id: "A", label: "Maximales Haltbarkeitsdatum" },
        { id: "B", label: "Mindesthaltbarkeitsdatum" },
        { id: "C", label: "Mittleres Haltbarkeitsdatum" },
        { id: "D", label: "Mindestens haltbar durch" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    // Technik-Fails
    {
      id: "q-te-01",
      type: QuestionType.MultipleChoice,
      text: "Was war der grosse Nachteil eines Discman beim Gehen?",
      options: [
        { id: "A", label: "Er war zu schwer fuer Hosentaschen" },
        { id: "B", label: "Songs sprangen wegen Erschuetterungen" },
        { id: "C", label: "Der Akku hielt nur 30 Minuten" },
        { id: "D", label: "Er spielte nur CD-Rs ab" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-te-02",
      type: QuestionType.MultipleChoice,
      text: "Was war T9 bei Handys?",
      options: [
        { id: "A", label: "Ein Betriebssystem fuer Nokia-Geraete" },
        { id: "B", label: "Eine Verschluesselungstechnologie" },
        { id: "C", label: "Eine Texteingabehilfe zur Worterkennung auf Nummerntastaturen" },
        { id: "D", label: "Ein Messenger-Dienst" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-te-03",
      type: QuestionType.MultipleChoice,
      text: "Welche Marke steckt hinter dem Kult-Handy 3310?",
      options: [
        { id: "A", label: "Siemens" },
        { id: "B", label: "Ericsson" },
        { id: "C", label: "Motorola" },
        { id: "D", label: "Nokia" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
  ],
};

export function getDefaultQuiz(): Quiz {
  return MILLENNIALS_QUIZ;
}
