import { QuestionType, type Quiz } from "@quiz/shared-types";

const MILLENNIALS_QUIZ: Quiz = {
  id: "millennials-quiz-001",
  title: "Millennials-Quiz",
  questions: [
    // Harry Potter
    {
      id: "q-hp-01",
      type: QuestionType.MultipleChoice,
      text: "Wie lautet das erste Gryffindor-Passwort im ersten Harry-Potter-Film?",
      options: [
        { id: "A", label: "Caput Draconis" },
        { id: "B", label: "Wingardium Leviosa" },
        { id: "C", label: "Lumos Solem" },
        { id: "D", label: "Ohrenschmalz" },
      ],
      correctOptionId: "A",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-hp-02",
      type: QuestionType.MultipleChoice,
      text: "Welches Körperteil bricht Harry sich beim Quidditch-Spiel in 'Die Kammer des Schreckens', bevor Lockhart hilft?",
      options: [
        { id: "A", label: "Den linken Arm" },
        { id: "B", label: "Den rechten Arm" },
        { id: "C", label: "Das Schlüsselbein" },
        { id: "D", label: "Das Handgelenk" },
      ],
      correctOptionId: "B",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-hp-03",
      type: QuestionType.MultipleChoice,
      text: "Welchen Drachen bekommt Harry in der ersten Aufgabe des Trimagischen Turniers?",
      options: [
        { id: "A", label: "Den chinesischen Feuerball" },
        { id: "B", label: "Den walisischen Grünschwanz" },
        { id: "C", label: "Den schwedischen Kurzschnauzer" },
        { id: "D", label: "Den ungarischen Hornschwanz" },
      ],
      correctOptionId: "D",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-hp-04",
      type: QuestionType.MultipleChoice,
      text: "Wie heißt das Magazin, das Xenophilius Lovegood herausgibt?",
      options: [
        { id: "A", label: "Der Klitterer" },
        { id: "B", label: "Der Tagesprophet" },
        { id: "C", label: "Hexenwoche" },
        { id: "D", label: "Der Abendprophet" },
      ],
      correctOptionId: "A",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-hp-05",
      type: QuestionType.MultipleChoice,
      text: "Welches Tier erscheint patronusförmig bei Snapes Nachricht an Harry im Wald?",
      options: [
        { id: "A", label: "Ein Hirsch" },
        { id: "B", label: "Eine Hirschkuh" },
        { id: "C", label: "Ein Otter" },
        { id: "D", label: "Ein Wolf" },
      ],
      correctOptionId: "B",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-hp-06",
      type: QuestionType.MultipleChoice,
      text: "Wie heißt der Zauberspruch, mit dem Harry Draco im sechsten Film schwer verletzt?",
      options: [
        { id: "A", label: "Crucio" },
        { id: "B", label: "Expelliarmus" },
        { id: "C", label: "Sectumsempra" },
        { id: "D", label: "Avada Kedavra" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-hp-07",
      type: QuestionType.MultipleChoice,
      text: "Welchen Zauberspruch benutzt Hermine im ersten Film, um die Teufelsschlinge zu besiegen?",
      options: [
        { id: "A", label: "Alohomora" },
        { id: "B", label: "Expecto Patronum" },
        { id: "C", label: "Lumos Solem" },
        { id: "D", label: "Reparo" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-hp-08",
      type: QuestionType.MultipleChoice,
      text: "Wie viele unverzeihliche Flüche nennt Professor Moody im vierten Harry-Potter-Film?",
      options: [
        { id: "A", label: "Zwei" },
        { id: "B", label: "Drei" },
        { id: "C", label: "Fünf" },
        { id: "D", label: "Sieben" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-hp-09",
      type: QuestionType.MultipleChoice,
      text: "Wie lautet der zweite Vorname von Harry Potter?",
      options: [
        { id: "A", label: "Thomas" },
        { id: "B", label: "George" },
        { id: "C", label: "James" },
        { id: "D", label: "William" },
      ],
      correctOptionId: "C",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-hp-10",
      type: QuestionType.MultipleChoice,
      text: "Wie heißt der dreiköpfige Hund, der im ersten Film die Falltür bewacht?",
      options: [
        { id: "A", label: "Cerberus" },
        { id: "B", label: "Fluffy" },
        { id: "C", label: "Bruno" },
        { id: "D", label: "Kralle" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-hp-11",
      type: QuestionType.MultipleChoice,
      text: "Welche weltbekannte Schauspielerin wurde für die Rolle der Helena Ravenclaw angefragt, bevor Kelly Macdonald sie spielte?",
      options: [
        { id: "A", label: "Keira Knightley" },
        { id: "B", label: "Cate Blanchett" },
        { id: "C", label: "Emma Thompson" },
        { id: "D", label: "Kate Winslet" },
      ],
      correctOptionId: "D",
      durationMs: 12_000,
      points: 3,
    },
    // Millennial-Slang & Internet-Fossilien
    {
      id: "q-sl-01",
      type: QuestionType.MultipleChoice,
      text: "Welches Geräusch machte ICQ bei einer neuen Nachricht?",
      options: [
        { id: "A", label: "Ein Ping" },
        { id: "B", label: "Ein Glöckchen" },
        { id: "C", label: "Uh-oh!" },
        { id: "D", label: "Ein Klopfen" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sl-02",
      type: QuestionType.MultipleChoice,
      text: "Welches deutsche soziale Netzwerk war für Schüler prägendster Treffpunkt vor Facebook?",
      options: [
        { id: "A", label: "MySpace" },
        { id: "B", label: "Xing" },
        { id: "C", label: "Studi17" },
        { id: "D", label: "SchülerVZ" },
      ],
      correctOptionId: "D",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-sl-03",
      type: QuestionType.MultipleChoice,
      text: "Was war 'gruscheln' bei StudiVZ?",
      options: [
        { id: "A", label: "Eine Funktion zum Teilen von Fotos" },
        { id: "B", label: "Ein Spiel im Netzwerk" },
        { id: "C", label: "Das Schreiben öffentlicher Pinnwand-Posts" },
        { id: "D", label: "Mischung aus grüßen und kuscheln – digitaler Fremdschamkontakt" },
      ],
      correctOptionId: "D",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-sl-04",
      type: QuestionType.MultipleChoice,
      text: "Welche Schriftart galt in Kettenbriefen und peinlichen Profilen als Pflicht-Klischee?",
      options: [
        { id: "A", label: "Arial" },
        { id: "B", label: "Comic Sans" },
        { id: "C", label: "Papyrus" },
        { id: "D", label: "Times New Roman" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sl-05",
      type: QuestionType.MultipleChoice,
      text: "Was war mit 'ASL?' in alten Chats gemeint?",
      options: [
        { id: "A", label: "Account, Status, Link" },
        { id: "B", label: "Age, Sex, Location" },
        { id: "C", label: "Always Stay Logged-in" },
        { id: "D", label: "Assigned Screen Language" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-sl-06",
      type: QuestionType.MultipleChoice,
      text: "Was war der 'Nudge' bei MSN Messenger?",
      options: [
        { id: "A", label: "Eine Möglichkeit, Bilder direkt zu teilen" },
        { id: "B", label: "Eine Funktion, die das Chatfenster des Gegenübers schüttelte" },
        { id: "C", label: "Der Offline-Status-Sound" },
        { id: "D", label: "Eine animierte Freundschaftsanfrage" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-sl-07",
      type: QuestionType.MultipleChoice,
      text: "Wofür stand 'brb' in alten Chats?",
      options: [
        { id: "A", label: "Back room buddy" },
        { id: "B", label: "Bring real beer" },
        { id: "C", label: "Be right back" },
        { id: "D", label: "Be really bored" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sl-08",
      type: QuestionType.MultipleChoice,
      text: "Was bedeutet 'YOLO'?",
      options: [
        { id: "A", label: "Your online life online" },
        { id: "B", label: "You only live once" },
        { id: "C", label: "You obviously love others" },
        { id: "D", label: "You owe, live on" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sl-09",
      type: QuestionType.MultipleChoice,
      text: "Wofür nutzte man '404' als Witz im Netzjargon?",
      options: [
        { id: "A", label: "Dass jemand offline gegangen ist" },
        { id: "B", label: "Dass jemand im Forum gesperrt wurde" },
        { id: "C", label: "Dass jemand nichts kapiert oder nicht gefunden wird" },
        { id: "D", label: "Dass jemand verliebt ist" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-sl-10",
      type: QuestionType.MultipleChoice,
      text: "Was war '1337' bzw. 'leet' im Internet-Jargon?",
      options: [
        { id: "A", label: "Ein Elite-Gaming-Clan-Präfix" },
        { id: "B", label: "Eine Hacker-/Gamer-Schreibweise mit Zahlen statt Buchstaben" },
        { id: "C", label: "Ein Modding-Tool für PC-Spiele" },
        { id: "D", label: "Ein Cheat-Code für Counter-Strike" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    // Dating-Slang & Beziehungs-Bullshit
    {
      id: "q-ds-01",
      type: QuestionType.MultipleChoice,
      text: "Was bedeutet 'Netflix & Chill' im Internet-Slang meistens wirklich?",
      options: [
        { id: "A", label: "Gemeinsam entspannt eine Serie bingen" },
        { id: "B", label: "Den Abend mit Popcorn und Film verbringen" },
        { id: "C", label: "Sexuelle oder romantische Annäherung statt Serien schauen" },
        { id: "D", label: "Ungestört vom Partner Videospiele spielen" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-ds-02",
      type: QuestionType.MultipleChoice,
      text: "Wofür steht 'ghosting' beim Dating?",
      options: [
        { id: "A", label: "Heimliches Stalken über Social Media" },
        { id: "B", label: "Plötzlicher Kontaktabbruch ohne Erklärung" },
        { id: "C", label: "Das Versenden anonymer Nachrichten" },
        { id: "D", label: "Jemanden auf allen Plattformen blockieren" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-ds-03",
      type: QuestionType.MultipleChoice,
      text: "Was meint 'catfishing'?",
      options: [
        { id: "A", label: "Das anonyme Verbreiten von Gerüchten im Netz" },
        { id: "B", label: "Eine Dating-App speziell für Outdoor-Fans" },
        { id: "C", label: "Freunde ungefragt in Fotos taggen" },
        {
          id: "D",
          label: "Jemand gibt online eine falsche Identität vor, oft romantisch/manipulativ",
        },
      ],
      correctOptionId: "D",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-ds-04",
      type: QuestionType.MultipleChoice,
      text: "Was meint 'love bombing'?",
      options: [
        { id: "A", label: "Das gleichzeitige Daten mehrerer Personen" },
        { id: "B", label: "Übermäßige Zuwendung am Anfang einer Beziehung, oft manipulativ" },
        { id: "C", label: "Eine Strategie, bei der man absichtlich kalt bleibt" },
        { id: "D", label: "Unangemessen anzügliche Direktnachrichten schicken" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-ds-05",
      type: QuestionType.MultipleChoice,
      text: "Was bedeutet 'NSFW'?",
      options: [
        { id: "A", label: "New Social Feed Weekly" },
        { id: "B", label: "No Sharing For Women" },
        { id: "C", label: "Not Safe For Work" },
        { id: "D", label: "Need Some Fun Words" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-ds-06",
      type: QuestionType.MultipleChoice,
      text: "Was bezeichnet 'situationship'?",
      options: [
        { id: "A", label: "Eine Fernbeziehung ohne echte Treffen" },
        { id: "B", label: "Eine offene Beziehung mit festem Regelwerk" },
        { id: "C", label: "Eine undefinierte romantisch-sexuelle Verbindung ohne Beziehungslabel" },
        { id: "D", label: "Das gleichzeitige Daten mehrerer Personen" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    // 90er/00er Trash-TV
    {
      id: "q-tv-01",
      type: QuestionType.MultipleChoice,
      text: "Wie hieß das deutsche Dschungelcamp offiziell?",
      options: [
        { id: "A", label: "Überleben im Dschungel" },
        { id: "B", label: "Dschungel der Stars" },
        { id: "C", label: "Wild und Promi" },
        { id: "D", label: "Ich bin ein Star – Holt mich hier raus!" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-tv-02",
      type: QuestionType.MultipleChoice,
      text: "Wie hieß das Jamba-Frosch-Maskottchen mit dem unvergesslichen Klingelton-Song?",
      options: [
        { id: "A", label: "Crazy Frog" },
        { id: "B", label: "Happy Toad" },
        { id: "C", label: "Ringy" },
        { id: "D", label: "Frogster" },
      ],
      correctOptionId: "A",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-tv-03",
      type: QuestionType.MultipleChoice,
      text: "Wie hieß der Jamba-/Jamster-Hase hinter dem berüchtigten Kuschel-Song?",
      options: [
        { id: "A", label: "Sweety" },
        { id: "B", label: "Baby Vuvu" },
        { id: "C", label: "Schnuffel" },
        { id: "D", label: "Husky" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-tv-04",
      type: QuestionType.MultipleChoice,
      text: "Welche legendäre Werbung prägt den Spruch 'Isch abe gar keine Auto'?",
      options: [
        { id: "A", label: "Die Carglass-Werbung" },
        { id: "B", label: "Eine Renault-Clio-Werbung" },
        { id: "C", label: "Die Nescafé-Cappuccino-Werbung mit Angelo" },
        { id: "D", label: "Die Seitenbacher-Werbung" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-tv-05",
      type: QuestionType.MultipleChoice,
      text: "Welche MTV-Show durchleuchtete Schlafzimmer mit UV-Licht, um Dates zu blamieren?",
      options: [
        { id: "A", label: "Next" },
        { id: "B", label: "Parental Control" },
        { id: "C", label: "Room Raiders" },
        { id: "D", label: "Date My Mom" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-tv-06",
      type: QuestionType.MultipleChoice,
      text: "Bei welcher MTV-Dating-Show saß eine Person im Bus und sortierte Kandidaten direkt unterwegs aus?",
      options: [
        { id: "A", label: "Room Raiders" },
        { id: "B", label: "Next" },
        { id: "C", label: "Dismissed" },
        { id: "D", label: "Date My Mom" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-tv-07",
      type: QuestionType.MultipleChoice,
      text: "Welche deutsche Gerichtsshow wurde mit ihrer Titelrichterin zum Nachmittags-Phänomen?",
      options: [
        { id: "A", label: "Richter Alexander Hold" },
        { id: "B", label: "Vera am Mittag" },
        { id: "C", label: "Richterin Barbara Salesch" },
        { id: "D", label: "Das Jugendgericht" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-tv-08",
      type: QuestionType.MultipleChoice,
      text: "Welche ProSieben-Show machte Model-Castings und toxischen Ehrgeiz zum Volkssport?",
      options: [
        { id: "A", label: "Popstars" },
        { id: "B", label: "DSDS" },
        { id: "C", label: "Germany's Next Topmodel" },
        { id: "D", label: "The Voice of Germany" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-tv-09",
      type: QuestionType.MultipleChoice,
      text: "Welcher Sender ließ nachts Zuschauer für offensichtliche Rätsel teures Telefongeld verbrennen?",
      options: [
        { id: "A", label: "DSF" },
        { id: "B", label: "9Live" },
        { id: "C", label: "VIVA" },
        { id: "D", label: "Tele 5" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-tv-10",
      type: QuestionType.MultipleChoice,
      text: "Welche langjährige deutsche Talkshow lief mit Britt Hagedorn?",
      options: [
        { id: "A", label: "Arabella" },
        { id: "B", label: "Vera am Mittag" },
        { id: "C", label: "Britt – Der Talk um eins" },
        { id: "D", label: "TV Total" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-tv-11",
      type: QuestionType.MultipleChoice,
      text: "Wie hieß das penetrant gelbe Jamba-Küken aus der TV-Werbung – nicht Crazy Frog, nicht Schnuffel?",
      options: [
        { id: "A", label: "Chicky" },
        { id: "B", label: "Tweety" },
        { id: "C", label: "Sweety" },
        { id: "D", label: "Froggy" },
      ],
      correctOptionId: "C",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-tv-12",
      type: QuestionType.MultipleChoice,
      text: "Wer war der allererste Dschungelkönig bei 'Ich bin ein Star – Holt mich hier raus!'?",
      options: [
        { id: "A", label: "Désirée Nick" },
        { id: "B", label: "Costa Cordalis" },
        { id: "C", label: "Ross Antony" },
        { id: "D", label: "Ingrid van Bergen" },
      ],
      correctOptionId: "B",
      durationMs: 12_000,
      points: 3,
    },
    // Saufen, Feiern & Jugend-Drinks
    {
      id: "q-dr-01",
      type: QuestionType.MultipleChoice,
      text: "Welcher Alkopop war in den 2000ern das Partygetränk schlechthin in Deutschland?",
      options: [
        { id: "A", label: "Bacardi Breezer" },
        { id: "B", label: "WKD Blue" },
        { id: "C", label: "Desperados" },
        { id: "D", label: "Smirnoff Ice" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-dr-02",
      type: QuestionType.MultipleChoice,
      text: "Woraus besteht ein klassischer Vodka-E?",
      options: [
        { id: "A", label: "Vodka und Limo" },
        { id: "B", label: "Vodka und Energy Drink" },
        { id: "C", label: "Vodka und Tonic" },
        { id: "D", label: "Vodka und Orangensaft" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-dr-03",
      type: QuestionType.MultipleChoice,
      text: "Was bezeichnet 'Vorglühen' im Partykontext?",
      options: [
        { id: "A", label: "Den ersten Tanz des Abends eröffnen" },
        { id: "B", label: "Sich mit Sport vor der Party aufwärmen" },
        { id: "C", label: "Vor dem Ausgehen zuhause oder günstig vortrinken" },
        { id: "D", label: "Die Stimmung mit Musikauswahl aufheizen" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-dr-04",
      type: QuestionType.MultipleChoice,
      text: "Was ist 'Flunkyball'?",
      options: [
        { id: "A", label: "Ein Brettspiel mit Würfeln und Schnapskarten" },
        { id: "B", label: "Ein Volleyball-Trinkspiel für Verlierer" },
        { id: "C", label: "Ein Trinkspiel, bei dem Bälle auf eine Flasche geworfen werden" },
        { id: "D", label: "Ein Dart-Trinkspiel aus den 1990ern" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-dr-05",
      type: QuestionType.MultipleChoice,
      text: "Was bedeutet 'Filmriss' umgangssprachlich?",
      options: [
        { id: "A", label: "Ein Film, der im Kino technisch abbricht" },
        { id: "B", label: "Das Einschlafen beim Film" },
        { id: "C", label: "Ein misslungenes Erlebnis des Abends" },
        { id: "D", label: "Erinnerungslücken durch zu hohen Alkoholkonsum" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-dr-06",
      type: QuestionType.MultipleChoice,
      text: "Was ist ein 'Herrengedeck' im klassischen Kneipenverständnis?",
      options: [
        { id: "A", label: "Bier plus Limo (Diesel)" },
        { id: "B", label: "Bier plus Schnaps" },
        { id: "C", label: "Kaffee mit Schuss" },
        { id: "D", label: "Eine Flasche Wein mit Käsebrett" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-dr-07",
      type: QuestionType.MultipleChoice,
      text: "Woraus besteht ein klassischer Cuba Libre?",
      options: [
        { id: "A", label: "Tequila, Cola und Zitrone" },
        { id: "B", label: "Vodka, Ginger Beer und Limette" },
        { id: "C", label: "Rum, Cola und Limette" },
        { id: "D", label: "Rum, Orangensaft und Grenadine" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    // Absurde Skandale & Popkultur-Meltdowns
    {
      id: "q-sk-01",
      type: QuestionType.MultipleChoice,
      text: "Welche Pop-Ikone rasierte sich 2007 öffentlich den Kopf und wurde damit zur Boulevard-Klischee-Krise?",
      options: [
        { id: "A", label: "Amy Winehouse" },
        { id: "B", label: "Paris Hilton" },
        { id: "C", label: "Britney Spears" },
        { id: "D", label: "Lindsay Lohan" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sk-02",
      type: QuestionType.MultipleChoice,
      text: "Wer riss Taylor Swift bei den MTV VMAs 2009 das Mikrofon weg, um Beyoncé zu loben?",
      options: [
        { id: "A", label: "Chris Brown" },
        { id: "B", label: "Jay-Z" },
        { id: "C", label: "Kanye West" },
        { id: "D", label: "T.I." },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sk-03",
      type: QuestionType.MultipleChoice,
      text: "Welcher Hollywoodstar sprang 2005 in der Oprah-Winfrey-Show auf dem Sofa herum, um seine Liebe zu erklären?",
      options: [
        { id: "A", label: "Will Smith" },
        { id: "B", label: "Tom Cruise" },
        { id: "C", label: "Jim Carrey" },
        { id: "D", label: "Nicolas Cage" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-sk-04",
      type: QuestionType.MultipleChoice,
      text: "Welche Sängerin wurde durch ihren Song 'Rehab' und ihre öffentliche Suchtproblematik zur tragischen Ikone?",
      options: [
        { id: "A", label: "Lily Allen" },
        { id: "B", label: "Adele" },
        { id: "C", label: "Amy Winehouse" },
        { id: "D", label: "Duffy" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sk-05",
      type: QuestionType.MultipleChoice,
      text: "Welcher Tour-de-France-Sieger wurde zur größten Doping-Schande der 2000er/2010er?",
      options: [
        { id: "A", label: "Jan Ullrich" },
        { id: "B", label: "Marco Pantani" },
        { id: "C", label: "Floyd Landis" },
        { id: "D", label: "Lance Armstrong" },
      ],
      correctOptionId: "D",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-sk-06",
      type: QuestionType.MultipleChoice,
      text: "Mit welchem Tier trat Britney Spears 2001 bei den MTV VMAs auf der Bühne auf?",
      options: [
        { id: "A", label: "Mit einem weißen Tiger" },
        { id: "B", label: "Mit einer Albino-Python" },
        { id: "C", label: "Mit einem Papagei" },
        { id: "D", label: "Mit einem Löwenwelpen" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-sk-07",
      type: QuestionType.MultipleChoice,
      text: "Welcher Schauspieler gab seinem Sohn den bis heute unfassbaren Namen 'Pilot Inspektor'?",
      options: [
        { id: "A", label: "Jason Lee" },
        { id: "B", label: "Nicolas Cage" },
        { id: "C", label: "Bob Geldof" },
        { id: "D", label: "Sylvester Stallone" },
      ],
      correctOptionId: "A",
      durationMs: 12_000,
      points: 3,
    },
    // Gaming
    {
      id: "q-gm-01",
      type: QuestionType.MultipleChoice,
      text: "Welcher Gegenstand ruiniert in Mario Kart gezielt den Erstplatzierten?",
      options: [
        { id: "A", label: "Der rote Panzer" },
        { id: "B", label: "Der Blitz" },
        { id: "C", label: "Der Stern" },
        { id: "D", label: "Der blaue Panzer" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-gm-02",
      type: QuestionType.MultipleChoice,
      text: "Was passierte in 'Die Sims', wenn man die Poolleiter entfernte?",
      options: [
        { id: "A", label: "Der Sim wurde unsichtbar" },
        { id: "B", label: "Der Sim konnte ertrinken" },
        { id: "C", label: "Das Spiel stürzte ab" },
        { id: "D", label: "Der Sim teleportierte sich" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-gm-03",
      type: QuestionType.MultipleChoice,
      text: "Was war der größte psychologische Terror beim Tamagotchi?",
      options: [
        { id: "A", label: "Es konnte nicht pausiert werden" },
        { id: "B", label: "Das Display war zu klein" },
        { id: "C", label: "Es konnte sterben, wenn man es vernachlässigte" },
        { id: "D", label: "Die Batterien waren nach zwei Tagen leer" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-gm-04",
      type: QuestionType.MultipleChoice,
      text: "Welches Spiel ist für den Satz 'Finish him!' bekannt?",
      options: [
        { id: "A", label: "Street Fighter" },
        { id: "B", label: "Tekken" },
        { id: "C", label: "Mortal Kombat" },
        { id: "D", label: "Soul Calibur" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-gm-05",
      type: QuestionType.MultipleChoice,
      text: "Welche Figur aus 'The Legend of Zelda' ist trotz der Verwirrung gar nicht Zelda?",
      options: [
        { id: "A", label: "Ganon" },
        { id: "B", label: "Impa" },
        { id: "C", label: "Link" },
        { id: "D", label: "Epona" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-gm-06",
      type: QuestionType.MultipleChoice,
      text: "Welches Pokémon entwickelt sich aus Kadabra, aber nur durch Tausch?",
      options: [
        { id: "A", label: "Mewtu" },
        { id: "B", label: "Abra" },
        { id: "C", label: "Simsala" },
        { id: "D", label: "Habitak" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-gm-07",
      type: QuestionType.MultipleChoice,
      text: "Welche Konsole war für das berüchtigte 'Rote Ringe des Todes'-Problem bekannt?",
      options: [
        { id: "A", label: "PlayStation 3" },
        { id: "B", label: "Xbox 360" },
        { id: "C", label: "Nintendo Wii" },
        { id: "D", label: "Sega Dreamcast" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-gm-08",
      type: QuestionType.MultipleChoice,
      text: "In welchem Spiel war 'rosebud' ein bekannter Geld-Cheat?",
      options: [
        { id: "A", label: "SimCity" },
        { id: "B", label: "Age of Empires" },
        { id: "C", label: "Die Sims" },
        { id: "D", label: "Rollercoaster Tycoon" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-gm-09",
      type: QuestionType.MultipleChoice,
      text: "Was war eine 'LAN-Party'?",
      options: [
        { id: "A", label: "Ein offizielles E-Sport-Turnier mit Preisgeld" },
        { id: "B", label: "Eine Spielemesse für Neuerscheinungen" },
        { id: "C", label: "Ein Treffen, bei dem alle eigene PCs mitbrachten und lokal zockten" },
        { id: "D", label: "Ein Online-Event für globale Multiplayer-Sessions" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-gm-10",
      type: QuestionType.MultipleChoice,
      text: "Wie heißt der blaue Panzer offiziell auf Deutsch laut Nintendo?",
      options: [
        { id: "A", label: "Stachi-Panzer" },
        { id: "B", label: "Blau-Panzer" },
        { id: "C", label: "Dorn-Panzer" },
        { id: "D", label: "Spitzen-Panzer" },
      ],
      correctOptionId: "A",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-gm-11",
      type: QuestionType.MultipleChoice,
      text: "Was bewirkte der GTA San Andreas Cheat-Code 'HESOYAM'?",
      options: [
        { id: "A", label: "Alle Waffen freischalten" },
        { id: "B", label: "Unbegrenzte Munition aktivieren" },
        { id: "C", label: "Volle Gesundheit, Rüstung und 250.000 Dollar" },
        { id: "D", label: "Fahndungslevel auf null setzen" },
      ],
      correctOptionId: "C",
      durationMs: 12_000,
      points: 3,
    },
    // Musik
    {
      id: "q-mu-01",
      type: QuestionType.MultipleChoice,
      text: "Welche Band machte 'Durch den Monsun' 2005 in Deutschland zum Hit?",
      options: [
        { id: "A", label: "Tokio Hotel" },
        { id: "B", label: "My Chemical Romance" },
        { id: "C", label: "Scooter" },
        { id: "D", label: "Silbermond" },
      ],
      correctOptionId: "A",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-mu-02",
      type: QuestionType.MultipleChoice,
      text: "Welche Band veröffentlichte 'Welcome to the Black Parade'?",
      options: [
        { id: "A", label: "Fall Out Boy" },
        { id: "B", label: "Panic! at the Disco" },
        { id: "C", label: "My Chemical Romance" },
        { id: "D", label: "Simple Plan" },
      ],
      correctOptionId: "C",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-mu-03",
      type: QuestionType.MultipleChoice,
      text: "Welches Originalstück hat Crazy Frog 2005 mit seiner Nervensäge-Version verewigt?",
      options: [
        { id: "A", label: "Blue (Da Ba Dee)" },
        { id: "B", label: "Axel F" },
        { id: "C", label: "Sandstorm" },
        { id: "D", label: "Popcorn" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-mu-04",
      type: QuestionType.MultipleChoice,
      text: "Wer hatte den 2000er-Hit 'Dragostea Din Tei' (aka Numa-Numa-Song)?",
      options: [
        { id: "A", label: "Eiffel 65" },
        { id: "B", label: "Basshunter" },
        { id: "C", label: "O-Zone" },
        { id: "D", label: "t.A.T.u." },
      ],
      correctOptionId: "C",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-mu-05",
      type: QuestionType.MultipleChoice,
      text: "Welche Gruppe ist für 'Blue (Da Ba Dee)' bekannt?",
      options: [
        { id: "A", label: "Aqua" },
        { id: "B", label: "Eiffel 65" },
        { id: "C", label: "Vengaboys" },
        { id: "D", label: "Cascada" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-mu-06",
      type: QuestionType.MultipleChoice,
      text: "Wie heißt der Sänger von Tokio Hotel?",
      options: [
        { id: "A", label: "Tom Kaulitz" },
        { id: "B", label: "Bill Kaulitz" },
        { id: "C", label: "Georg Listing" },
        { id: "D", label: "David Jost" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-mu-07",
      type: QuestionType.MultipleChoice,
      text: "Welche Boyband sang 'Bye Bye Bye'?",
      options: [
        { id: "A", label: "Backstreet Boys" },
        { id: "B", label: "Westlife" },
        { id: "C", label: "*NSYNC" },
        { id: "D", label: "Take That" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-mu-08",
      type: QuestionType.MultipleChoice,
      text: "Wie hieß 'Schnappi, das kleine ___'?",
      options: [
        { id: "A", label: "Nilpferd" },
        { id: "B", label: "Känguru" },
        { id: "C", label: "Krokodil" },
        { id: "D", label: "Dinosaurier" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-mu-09",
      type: QuestionType.MultipleChoice,
      text: "Welche Band veröffentlichte den Song 'In the End'?",
      options: [
        { id: "A", label: "Limp Bizkit" },
        { id: "B", label: "Papa Roach" },
        { id: "C", label: "System of a Down" },
        { id: "D", label: "Linkin Park" },
      ],
      correctOptionId: "D",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-mu-10",
      type: QuestionType.MultipleChoice,
      text: "Welche Sängerin wurde mit 'Complicated' zur Pop-Punk-Ikone der frühen 2000er?",
      options: [
        { id: "A", label: "Pink" },
        { id: "B", label: "Avril Lavigne" },
        { id: "C", label: "Kelly Clarkson" },
        { id: "D", label: "Alanis Morissette" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-mu-11",
      type: QuestionType.MultipleChoice,
      text: "Welcher Song war 1998 der erste Mainstream-Hit, der Autotune als Effekt einsetzte?",
      options: [
        { id: "A", label: "Cher – 'Believe'" },
        { id: "B", label: "T-Pain – 'Buy U a Drank'" },
        { id: "C", label: "Daft Punk – 'Harder Better Faster Stronger'" },
        { id: "D", label: "Eiffel 65 – 'Blue (Da Ba Dee)'" },
      ],
      correctOptionId: "A",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-mu-12",
      type: QuestionType.MultipleChoice,
      text: "Welcher Manager baute sowohl die Backstreet Boys als auch *NSYNC auf – und betrog beide?",
      options: [
        { id: "A", label: "Simon Fuller" },
        { id: "B", label: "Lou Pearlman" },
        { id: "C", label: "Irving Azoff" },
        { id: "D", label: "Clive Davis" },
      ],
      correctOptionId: "B",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-mu-13",
      type: QuestionType.MultipleChoice,
      text: "Wer war der Leadsänger von Linkin Park?",
      options: [
        { id: "A", label: "Chester Bennington" },
        { id: "B", label: "Mike Shinoda" },
        { id: "C", label: "Dave Grohl" },
        { id: "D", label: "Billy Joe Armstrong" },
      ],
      correctOptionId: "A",
      durationMs: 15_000,
      points: 2,
    },
    // Adulting Fails
    {
      id: "q-ad-01",
      type: QuestionType.MultipleChoice,
      text: "Was passiert typischerweise, wenn man rote und weiße Wäsche zusammen wäscht?",
      options: [
        { id: "A", label: "Gar nichts, ist ein Mythos" },
        { id: "B", label: "Die rote Farbe verblasst" },
        { id: "C", label: "Die Wäsche wird steif" },
        { id: "D", label: "Alles wird rosa – Verfärbungsrisiko" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-ad-02",
      type: QuestionType.MultipleChoice,
      text: "Was macht man mit einem Fettbrand auf dem Herd auf keinen Fall?",
      options: [
        { id: "A", label: "Deckel drauflegen" },
        { id: "B", label: "Mit Wasser löschen" },
        { id: "C", label: "Herd ausschalten" },
        { id: "D", label: "Feuerlöscher benutzen" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-ad-03",
      type: QuestionType.MultipleChoice,
      text: "Was bedeutet MHD auf Lebensmitteln?",
      options: [
        { id: "A", label: "Maximales Haltbarkeitsdatum" },
        { id: "B", label: "Mindesthaltbarkeitsdatum" },
        { id: "C", label: "Mittleres Haltbarkeitsdatum" },
        { id: "D", label: "Maximalhaltbarkeitsindex" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-ad-04",
      type: QuestionType.MultipleChoice,
      text: "Wofür steht ELSTER im deutschen Behördenkontext?",
      options: [
        { id: "A", label: "Eine Verordnung für Energiespargeräte" },
        { id: "B", label: "Das bundesweite Einwohnermelderegister online" },
        { id: "C", label: "Das elektronische Steuererklärungssystem der Finanzbehörden" },
        { id: "D", label: "Eine Naturschutz-Vogelschutzorganisation" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-ad-05",
      type: QuestionType.MultipleChoice,
      text: "Was ist der Sinn einer privaten Haftpflichtversicherung?",
      options: [
        { id: "A", label: "Schutz bei eigener Krankheit und Arbeitsausfall" },
        { id: "B", label: "Erstattung von gestohlenen eigenen Gegenständen" },
        { id: "C", label: "Absicherung gegen Schäden, die man anderen zufügt" },
        { id: "D", label: "Abdeckung von Mietschäden in der eigenen Wohnung" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-ad-06",
      type: QuestionType.MultipleChoice,
      text: "Wofür ist ein Pümpel (Gummisauger) da?",
      options: [
        { id: "A", label: "Zum Anbringen von Haken an Fliesen ohne Bohren" },
        { id: "B", label: "Zum Ausbeulen von Dellen in Türen oder Schränken" },
        { id: "C", label: "Zum Befüllen von Luftmatratzen ohne Pumpe" },
        { id: "D", label: "Zum Lösen von Verstopfungen in Toilette oder Abfluss" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    // Technik-Fails
    {
      id: "q-te-01",
      type: QuestionType.MultipleChoice,
      text: "Was war der große Nachteil eines Discman beim Gehen?",
      options: [
        { id: "A", label: "Er war zu schwer für Hosentaschen" },
        { id: "B", label: "Songs sprangen wegen Erschütterungen" },
        { id: "C", label: "Der Akku hielt nur 30 Minuten" },
        { id: "D", label: "Er spielte nur CD-Rs ab" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-te-02",
      type: QuestionType.MultipleChoice,
      text: "Was war T9 bei Handys?",
      options: [
        { id: "A", label: "Ein Betriebssystem für Nokia-Geräte" },
        { id: "B", label: "Eine Verschlüsselungstechnologie" },
        { id: "C", label: "Eine Texteingabehilfe zur Worterkennung auf Nummerntastaturen" },
        { id: "D", label: "Ein Messenger-Dienst" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-te-03",
      type: QuestionType.MultipleChoice,
      text: "Welche Marke steckt hinter dem Kult-Handy 3310?",
      options: [
        { id: "A", label: "Siemens" },
        { id: "B", label: "Ericsson" },
        { id: "C", label: "Motorola" },
        { id: "D", label: "Nokia" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-te-04",
      type: QuestionType.MultipleChoice,
      text: "Wofür war die Software 'Nero Burning ROM' bekannt?",
      options: [
        { id: "A", label: "Als kostenloser Medienplayer für MP3s" },
        { id: "B", label: "Als Brennsoftware für CDs und DVDs" },
        { id: "C", label: "Als Treibersoftware für Scanner und Drucker" },
        { id: "D", label: "Als Antivirenprogramm für Windows XP" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-te-05",
      type: QuestionType.MultipleChoice,
      text: "Welche Tauschbörse war neben Kazaa besonders berüchtigt für Viren und Fake-Dateien?",
      options: [
        { id: "A", label: "Napster" },
        { id: "B", label: "eMule" },
        { id: "C", label: "LimeWire" },
        { id: "D", label: "BitTorrent" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-te-06",
      type: QuestionType.MultipleChoice,
      text: "Welche Speicherkapazität hatte eine klassische 3,5-Zoll-Diskette?",
      options: [
        { id: "A", label: "700 MB" },
        { id: "B", label: "32 MB" },
        { id: "C", label: "256 KB" },
        { id: "D", label: "1,44 MB" },
      ],
      correctOptionId: "D",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-te-07",
      type: QuestionType.MultipleChoice,
      text: "Wofür war Winamp auf Windows bekannt?",
      options: [
        { id: "A", label: "Als kostenlose Videoschnittsoftware" },
        { id: "B", label: "Als Messenger-Dienst vor ICQ" },
        { id: "C", label: "Als populärer Medienplayer für MP3-Dateien" },
        { id: "D", label: "Als Brennsoftware für Audio-CDs" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-te-08",
      type: QuestionType.MultipleChoice,
      text: "Woran konnte man auf Kazaa erkennen, dass eine MP3-Datei gefälscht oder gefährlich war?",
      options: [
        { id: "A", label: "Die Datei hatte die Endung .exe statt .mp3" },
        { id: "B", label: "Der Dateiname war komplett in Großbuchstaben" },
        { id: "C", label: "Die Dateigröße war exakt 0 KB" },
        { id: "D", label: "Das Cover-Bild fehlte" },
      ],
      correctOptionId: "A",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-te-09",
      type: QuestionType.MultipleChoice,
      text: "Was passiert, wenn man einen starken Magneten an einen alten CRT-Monitor hält?",
      options: [
        { id: "A", label: "Der Monitor schaltet sich sofort aus" },
        { id: "B", label: "Das Bild verzerrt und verfärbt sich" },
        { id: "C", label: "Der Ton des Computers verstummt" },
        { id: "D", label: "Nichts – CRT sind magnetisch abgeschirmt" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    // Filme & Kino
    {
      id: "q-fi-01",
      type: QuestionType.MultipleChoice,
      text: "In welchem Film singt Céline Dion 'My Heart Will Go On'?",
      options: [
        { id: "A", label: "Dirty Dancing" },
        { id: "B", label: "Ghost" },
        { id: "C", label: "Titanic" },
        { id: "D", label: "Pretty Woman" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-fi-02",
      type: QuestionType.MultipleChoice,
      text: "Welcher Schauspieler spielte den Joker in 'The Dark Knight' (2008)?",
      options: [
        { id: "A", label: "Joaquin Phoenix" },
        { id: "B", label: "Jack Nicholson" },
        { id: "C", label: "Jared Leto" },
        { id: "D", label: "Heath Ledger" },
      ],
      correctOptionId: "D",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-fi-03",
      type: QuestionType.MultipleChoice,
      text: "Welcher Pixar-Film kam als erster in die Kinos?",
      options: [
        { id: "A", label: "A Bug's Life" },
        { id: "B", label: "Monsters, Inc." },
        { id: "C", label: "Toy Story" },
        { id: "D", label: "Findet Nemo" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-fi-04",
      type: QuestionType.MultipleChoice,
      text: "Aus welchem Film stammt der Satz 'Ich sehe tote Menschen'?",
      options: [
        { id: "A", label: "Der Exorzist" },
        { id: "B", label: "Ghostbusters" },
        { id: "C", label: "The Sixth Sense" },
        { id: "D", label: "The Others" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    // Essen & Kultur
    {
      id: "q-es-01",
      type: QuestionType.MultipleChoice,
      text: "Welche Frucht wurde zum Symbol der Millennial-Küche?",
      options: [
        { id: "A", label: "Mango" },
        { id: "B", label: "Avocado" },
        { id: "C", label: "Papaya" },
        { id: "D", label: "Kiwi" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-es-02",
      type: QuestionType.MultipleChoice,
      text: "Welcher Energy-Drink-Hersteller wirbt damit, dir 'Flügel zu verleihen'?",
      options: [
        { id: "A", label: "Monster" },
        { id: "B", label: "Burn" },
        { id: "C", label: "Rockstar" },
        { id: "D", label: "Red Bull" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-es-03",
      type: QuestionType.MultipleChoice,
      text: "Welcher TV-Koch wurde durch 'The Taste' und 'Kitchen Impossible' in Deutschland bekannt?",
      options: [
        { id: "A", label: "Alfons Schuhbeck" },
        { id: "B", label: "Tim Mälzer" },
        { id: "C", label: "Johann Lafer" },
        { id: "D", label: "Steffen Henssler" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    // Mode & Beauty
    {
      id: "q-mo-01",
      type: QuestionType.MultipleChoice,
      text: "Welche Hosen-Variante saß in den frühen 2000ern so tief, dass die Unterwäsche zu sehen war?",
      options: [
        { id: "A", label: "Schlaghosen" },
        { id: "B", label: "High-Waist-Jeans" },
        { id: "C", label: "Baggy Pants" },
        { id: "D", label: "Low-Rise-Jeans" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-mo-02",
      type: QuestionType.MultipleChoice,
      text: "Welche Farbe hatte das berühmte Livestrong-Silikonarmband von Lance Armstrong?",
      options: [
        { id: "A", label: "Rot" },
        { id: "B", label: "Blau" },
        { id: "C", label: "Grün" },
        { id: "D", label: "Gelb" },
      ],
      correctOptionId: "D",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-mo-03",
      type: QuestionType.MultipleChoice,
      text: "Welche Selfie-Pose wurde in den 2000ern zum absoluten Klischee?",
      options: [
        { id: "A", label: "Breites Lächeln" },
        { id: "B", label: "Augen verdrehen" },
        { id: "C", label: "Duckface (Schmollmund)" },
        { id: "D", label: "Daumen hoch" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },

    // ─── SCHÄTZFRAGEN (estimate) ───────────────────────────────────────────────

    {
      id: "q-est-01",
      type: QuestionType.Estimate,
      text: "Wie lang ist der durchschnittliche erigierte Penis weltweit? (in cm)",
      correctValue: 13.12,
      unit: "cm",
      context: "weltweit, Meta-Studie BJU International 2015",
      durationMs: 25_000,
      points: 5,
    },
    {
      id: "q-est-02",
      type: QuestionType.Estimate,
      text: "In welchem Alter hatten Deutsche im Schnitt das erste Mal Sex?",
      correctValue: 17.1,
      unit: "Jahre",
      context: "Deutschland, BZgA-Studie 2010",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-est-03",
      type: QuestionType.Estimate,
      text: "Wie viele Stunden täglich verbringt ein durchschnittlicher Deutscher mit dem Smartphone?",
      correctValue: 3.7,
      unit: "Stunden",
      context: "Deutschland, Statista 2023",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-est-04",
      text: "Wie viele Liter Bier trinkt ein Deutscher im Schnitt pro Jahr?",
      type: QuestionType.Estimate,
      correctValue: 80,
      unit: "Liter",
      context: "Deutschland, Statista 2022",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-est-05",
      type: QuestionType.Estimate,
      text: "Wie viele SMS hat ein deutsches Mobilfunknetz-Nutzer im Schnitt pro Monat verschickt – auf dem Höhepunkt der SMS-Nutzung?",
      correctValue: 50,
      unit: "SMS",
      context: "Deutschland, ca. 2012",
      durationMs: 25_000,
      points: 5,
    },
    {
      id: "q-est-06",
      type: QuestionType.Estimate,
      text: "Wie viele Kalorien hat ein Big Mac?",
      correctValue: 503,
      unit: "kcal",
      context: "McDonald's Deutschland, 2024",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-est-07",
      type: QuestionType.Estimate,
      text: "Wie alt ist das durchschnittliche Erstgebär-Alter von Frauen in Deutschland?",
      correctValue: 30.0,
      unit: "Jahre",
      context: "Deutschland, Statistisches Bundesamt 2022",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-est-08",
      type: QuestionType.Estimate,
      text: "Wie viele Minuten täglich verbringt der durchschnittliche Deutsche auf Social Media?",
      correctValue: 89,
      unit: "Minuten",
      context: "Deutschland, Statista 2023",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-est-09",
      type: QuestionType.Estimate,
      text: "Wie viele Kondome wurden in Deutschland pro Jahr auf dem Höhepunkt des Kondommarkts verkauft?",
      correctValue: 190_000_000,
      unit: "Stück",
      context: "Deutschland, ca. 2015, Bundeszentrale für gesundheitliche Aufklärung",
      durationMs: 25_000,
      points: 5,
    },
    {
      id: "q-est-10",
      type: QuestionType.Estimate,
      text: "Wie viel kostet eine Monatskarte für den ÖPNV in Berlin (AB-Bereich)?",
      correctValue: 86,
      unit: "Euro",
      context: "Berlin, BVG 2024",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-est-11",
      type: QuestionType.Estimate,
      text: "Wie viele Stunden schläft ein Erwachsener in Deutschland im Schnitt pro Nacht?",
      correctValue: 7.1,
      unit: "Stunden",
      context: "Deutschland, DAK-Gesundheitsreport 2022",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-est-12",
      type: QuestionType.Estimate,
      text: "Wie viele Kilogramm Schokolade isst ein Deutscher im Schnitt pro Jahr?",
      correctValue: 9.4,
      unit: "kg",
      context: "Deutschland, Süßwaren-Industrie Jahresbericht 2022",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-est-13",
      type: QuestionType.Estimate,
      text: "Wie viele Minuten verbringt ein Deutscher im Schnitt täglich auf YouTube?",
      correctValue: 28,
      unit: "Minuten",
      context: "Deutschland, GWI 2023",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-est-14",
      type: QuestionType.Estimate,
      text: "Wie viel Prozent der Deutschen haben schon mal eine One-Night-Stand gehabt?",
      correctValue: 42,
      unit: "%",
      context: "Deutschland, YouGov-Umfrage 2019",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-est-15",
      type: QuestionType.Estimate,
      text: "Wie viele Terabyte Daten werden täglich im weltweiten Internet übertragen?",
      correctValue: 5_000_000,
      unit: "TB",
      context: "weltweit, Cisco Annual Internet Report 2022",
      durationMs: 25_000,
      points: 5,
    },
    {
      id: "q-est-16",
      type: QuestionType.Estimate,
      text: "Wie viel Gigabyte hat das erste iPhone (Modell 1, 2007) in der größten Variante?",
      correctValue: 8,
      unit: "GB",
      context: "Apple, iPhone 1. Generation 2007",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-est-17",
      type: QuestionType.Estimate,
      text: "Wie viele Mal berührt ein Durchschnittsmensch sein Smartphone täglich?",
      correctValue: 2617,
      unit: "Mal",
      context: "weltweit, dscout Research 2016",
      durationMs: 25_000,
      points: 5,
    },
    {
      id: "q-est-18",
      type: QuestionType.Estimate,
      text: "Wie hoch ist das durchschnittliche Netto-Monatseinkommen eines Vollzeitbeschäftigten in Deutschland?",
      correctValue: 2240,
      unit: "Euro",
      context: "Deutschland, Statistisches Bundesamt 2022",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-est-19",
      type: QuestionType.Estimate,
      text: "Wie hoch ist der Body-Mass-Index (BMI) ab dem Übergewicht beginnt?",
      correctValue: 25,
      unit: "BMI",
      context: "WHO-Definition",
      durationMs: 15_000,
      points: 3,
    },
    {
      id: "q-est-20",
      type: QuestionType.Estimate,
      text: "Wie viel Prozent der Deutschen sind laut Statistik übergewichtig oder adipös?",
      correctValue: 53,
      unit: "%",
      context: "Deutschland, Robert Koch-Institut 2021",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-est-21",
      type: QuestionType.Estimate,
      text: "Wie viele Minuten dauert der durchschnittliche Geschlechtsakt (Penetration bis Orgasmus) laut Wissenschaft?",
      correctValue: 5.4,
      unit: "Minuten",
      context: "weltweit, Journal of Sexual Medicine 2005",
      durationMs: 25_000,
      points: 5,
    },
    {
      id: "q-est-22",
      type: QuestionType.Estimate,
      text: "Wie viel hat eine PlayStation 1 bei Launch 1995 in Deutschland gekostet (UVP)?",
      correctValue: 499,
      unit: "DM",
      context: "Deutschland, November 1995",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-est-23",
      type: QuestionType.Estimate,
      text: "Wie viel hat ein Nokia 3310 im Jahr 2000 neu gekostet?",
      correctValue: 499,
      unit: "DM",
      context: "Deutschland, ca. 2000–2001",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-est-24",
      type: QuestionType.Estimate,
      text: "Wie alt ist das durchschnittliche Heiratsalter von Männern in Deutschland?",
      correctValue: 34.6,
      unit: "Jahre",
      context: "Deutschland, Statistisches Bundesamt 2022",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-est-25",
      type: QuestionType.Estimate,
      text: "Wie viele Songs stehen auf Spotify zur Verfügung?",
      correctValue: 100_000_000,
      unit: "Songs",
      context: "Spotify, Stand 2024",
      durationMs: 25_000,
      points: 5,
    },

    // ─── MEHRHEITSFRAGEN (majority_guess) ─────────────────────────────────────

    {
      id: "q-mg-01",
      type: QuestionType.MajorityGuess,
      text: "Wie viel Prozent der Deutschen haben laut Umfrage schon mal ihren Partner oder ihre Partnerin beim Handy beschnüffelt?",
      correctValue: 34,
      unit: "%",
      context: "Deutschland, YouGov-Umfrage 2021",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-mg-02",
      type: QuestionType.MajorityGuess,
      text: "Wie viel Prozent der Deutschen geben an, regelmäßig online einzukaufen?",
      correctValue: 77,
      unit: "%",
      context: "Deutschland, Statista 2023",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-mg-03",
      type: QuestionType.MajorityGuess,
      text: "Wie viel Prozent der Deutschen haben laut Umfrage schon mal eine Diät gemacht?",
      correctValue: 55,
      unit: "%",
      context: "Deutschland, DAK 2021",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-mg-04",
      type: QuestionType.MajorityGuess,
      text: "Wie viel Prozent der 18- bis 34-Jährigen in Deutschland nutzen WhatsApp täglich?",
      correctValue: 87,
      unit: "%",
      context: "Deutschland, Statista 2023",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-mg-05",
      type: QuestionType.MajorityGuess,
      text: "Wie viel Prozent der Deutschen sagen, sie haben schon mal betrunken etwas bestellt und es am nächsten Tag bereut?",
      correctValue: 28,
      unit: "%",
      context: "Deutschland, YouGov-Umfrage 2020",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-mg-06",
      type: QuestionType.MajorityGuess,
      text: "Wie viel Prozent der Deutschen schlafen laut Umfrage mit dem Smartphone auf dem Nachttisch?",
      correctValue: 72,
      unit: "%",
      context: "Deutschland, Bitkom 2022",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-mg-07",
      type: QuestionType.MajorityGuess,
      text: "Wie viel Prozent aller deutschen Ehen enden laut Statistik in Scheidung?",
      correctValue: 37,
      unit: "%",
      context: "Deutschland, Statistisches Bundesamt 2022",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-mg-08",
      type: QuestionType.MajorityGuess,
      text: "Wie viel Prozent der Deutschen haben schon mal beim Ex auf Instagram gespioniert?",
      correctValue: 49,
      unit: "%",
      context: "Deutschland, YouGov-Umfrage 2022",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-mg-09",
      type: QuestionType.MajorityGuess,
      text: "Wie viel Prozent der Deutschen haben schon mal ihren Chef in den Gedanken verflucht?",
      correctValue: 63,
      unit: "%",
      context: "Deutschland, Stepstone-Umfrage 2021",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-mg-10",
      type: QuestionType.MajorityGuess,
      text: "Wie viel Prozent der Deutschen trinken täglich Kaffee?",
      correctValue: 77,
      unit: "%",
      context: "Deutschland, DKV 2022",
      durationMs: 15_000,
      points: 4,
    },
    {
      id: "q-mg-11",
      type: QuestionType.MajorityGuess,
      text: "Wie viel Prozent der Deutschen geben an, glücklich in ihrer Beziehung zu sein?",
      correctValue: 82,
      unit: "%",
      context: "Deutschland, Forsa-Umfrage 2021",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-mg-12",
      type: QuestionType.MajorityGuess,
      text: "Wie viel Prozent der Deutschen haben Angst vor dem Tod?",
      correctValue: 41,
      unit: "%",
      context: "Deutschland, Allensbach 2019",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-mg-13",
      type: QuestionType.MajorityGuess,
      text: "Wie viel Prozent der Deutschen haben schon mal beim Kegeln oder Fußball absolut keine Ahnung gehabt, aber so getan als ob?",
      correctValue: 44,
      unit: "%",
      context: "Deutschland, Yougov-Spaßumfrage 2020",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-mg-14",
      type: QuestionType.MajorityGuess,
      text: "Wie viel Prozent der Deutschen haben laut Umfrage ihre Eltern schon mal belogen, um nicht bei einem Familienfest zu erscheinen?",
      correctValue: 31,
      unit: "%",
      context: "Deutschland, Yougov 2021",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-mg-15",
      type: QuestionType.MajorityGuess,
      text: "Wie viel Prozent aller Deutschen nutzen Netflix mindestens einmal pro Woche?",
      correctValue: 43,
      unit: "%",
      context: "Deutschland, Statista 2023",
      durationMs: 20_000,
      points: 4,
    },

    // ─── RANKING-FRAGEN ────────────────────────────────────────────────────────

    {
      id: "q-rank-01",
      type: QuestionType.Ranking,
      text: "Sortiere diese Chat-Apps in der Reihenfolge, in der sie gestartet wurden (älteste zuerst).",
      items: [
        { id: "A", label: "WhatsApp (2009)" },
        { id: "B", label: "ICQ (1996)" },
        { id: "C", label: "Telegram (2013)" },
        { id: "D", label: "Signal (2014)" },
      ],
      correctOrder: ["B", "A", "C", "D"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-02",
      type: QuestionType.Ranking,
      text: "Sortiere diese Gaming-Konsolen nach Erscheinungsjahr in Deutschland (älteste zuerst).",
      items: [
        { id: "A", label: "PlayStation 2" },
        { id: "B", label: "Super Nintendo" },
        { id: "C", label: "Xbox 360" },
        { id: "D", label: "Nintendo 64" },
      ],
      correctOrder: ["B", "D", "A", "C"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-03",
      type: QuestionType.Ranking,
      text: "Sortiere diese Getränke nach Alkoholgehalt (niedrigster zuerst).",
      items: [
        { id: "A", label: "Vodka (40%)" },
        { id: "B", label: "Bier (5%)" },
        { id: "C", label: "Wein (12%)" },
        { id: "D", label: "Sekt (11%)" },
      ],
      correctOrder: ["B", "D", "C", "A"],
      durationMs: 25_000,
      points: 5,
    },
    {
      id: "q-rank-04",
      type: QuestionType.Ranking,
      text: "Sortiere diese Speichermedien nach Speicherkapazität (kleinste zuerst).",
      items: [
        { id: "A", label: "Blu-ray (25 GB)" },
        { id: "B", label: "Floppy Disk (1,44 MB)" },
        { id: "C", label: "DVD (4,7 GB)" },
        { id: "D", label: "CD (700 MB)" },
      ],
      correctOrder: ["B", "D", "C", "A"],
      durationMs: 25_000,
      points: 5,
    },
    {
      id: "q-rank-05",
      type: QuestionType.Ranking,
      text: "Sortiere diese deutschen TV-Shows nach Erstausstrahlung (älteste zuerst).",
      items: [
        { id: "A", label: "Germany's Next Topmodel (2006)" },
        { id: "B", label: "Big Brother (1999)" },
        { id: "C", label: "Deutschland sucht den Superstar (2002)" },
        { id: "D", label: "Dschungelcamp (2004)" },
      ],
      correctOrder: ["B", "C", "D", "A"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-06",
      type: QuestionType.Ranking,
      text: "Sortiere diese Popstars nach dem Jahr ihres Welterfolgs (frühestes Album/Single zuerst).",
      items: [
        { id: "A", label: "Billie Eilish" },
        { id: "B", label: "Spice Girls" },
        { id: "C", label: "Lady Gaga" },
        { id: "D", label: "Rihanna" },
      ],
      correctOrder: ["B", "D", "C", "A"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-07",
      type: QuestionType.Ranking,
      text: "Sortiere diese Fast-Food-Ketten nach Anzahl der Filialen in Deutschland (wenigste zuerst).",
      items: [
        { id: "A", label: "Burger King (~770)" },
        { id: "B", label: "Subway (~600)" },
        { id: "C", label: "McDonald's (~1.500)" },
        { id: "D", label: "KFC (~250)" },
      ],
      correctOrder: ["D", "B", "A", "C"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-08",
      type: QuestionType.Ranking,
      text: "Sortiere diese sozialen Netzwerke nach Gründungsjahr (ältestes zuerst).",
      items: [
        { id: "A", label: "Instagram (2010)" },
        { id: "B", label: "Facebook (2004)" },
        { id: "C", label: "TikTok (2016)" },
        { id: "D", label: "Twitter (2006)" },
      ],
      correctOrder: ["B", "D", "A", "C"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-09",
      type: QuestionType.Ranking,
      text: "Sortiere diese deutschen Städte nach Einwohnerzahl (kleinste zuerst).",
      items: [
        { id: "A", label: "Berlin" },
        { id: "B", label: "Frankfurt" },
        { id: "C", label: "München" },
        { id: "D", label: "Hamburg" },
      ],
      correctOrder: ["B", "C", "D", "A"],
      durationMs: 25_000,
      points: 5,
    },
    {
      id: "q-rank-10",
      type: QuestionType.Ranking,
      text: "Sortiere diese Kinofilme nach Erscheinungsjahr (ältester zuerst).",
      items: [
        { id: "A", label: "Avatar (2009)" },
        { id: "B", label: "Titanic (1997)" },
        { id: "C", label: "The Dark Knight (2008)" },
        { id: "D", label: "Inception (2010)" },
      ],
      correctOrder: ["B", "C", "A", "D"],
      durationMs: 30_000,
      points: 5,
    },
    {
      id: "q-rank-11",
      type: QuestionType.Ranking,
      text: "Sortiere diese Handys nach Erscheinungsjahr (ältestes zuerst).",
      items: [
        { id: "A", label: "iPhone 1 (2007)" },
        { id: "B", label: "Nokia 3310 (2000)" },
        { id: "C", label: "Motorola Razr V3 (2004)" },
        { id: "D", label: "Samsung Galaxy S1 (2010)" },
      ],
      correctOrder: ["B", "C", "A", "D"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-12",
      type: QuestionType.Ranking,
      text: "Sortiere diese Streaming-Dienste nach Anzahl weltweiter Abonnenten (wenigste zuerst, Stand 2023).",
      items: [
        { id: "A", label: "Netflix (~238 Mio.)" },
        { id: "B", label: "Disney+ (~157 Mio.)" },
        { id: "C", label: "Amazon Prime Video (~200 Mio.)" },
        { id: "D", label: "Spotify (~602 Mio.)" },
      ],
      correctOrder: ["B", "C", "A", "D"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-13",
      type: QuestionType.Ranking,
      text: "Sortiere diese Millennial-Symbole nach dem Jahr ihrer Einführung (ältestes zuerst).",
      items: [
        { id: "A", label: "Tamagotchi (1996)" },
        { id: "B", label: "MySpace (2003)" },
        { id: "C", label: "Napster (1999)" },
        { id: "D", label: "YouTube (2005)" },
      ],
      correctOrder: ["A", "C", "B", "D"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-14",
      type: QuestionType.Ranking,
      text: "Sortiere diese Bier-Marken nach Alkoholgehalt (niedrigster zuerst). Tipp: alle ähnlich, aber nicht gleich.",
      items: [
        { id: "A", label: "Beck's (4,9%)" },
        { id: "B", label: "Warsteiner (4,8%)" },
        { id: "C", label: "Paulaner Weißbier (5,5%)" },
        { id: "D", label: "Bitburger (4,8%)" },
      ],
      correctOrder: ["B", "D", "A", "C"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-15",
      type: QuestionType.Ranking,
      text: "Sortiere diese Harry-Potter-Bücher nach Seitenzahl (dünnste zuerst, deutsche Ausgabe).",
      items: [
        { id: "A", label: "Der Stein der Weisen (~335 S.)" },
        { id: "B", label: "Die Kammer des Schreckens (~351 S.)" },
        { id: "C", label: "Der Orden des Phönix (~1.019 S.)" },
        { id: "D", label: "Der Feuerkelch (~761 S.)" },
      ],
      correctOrder: ["A", "B", "D", "C"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-16",
      type: QuestionType.Ranking,
      text: "Sortiere diese Länder nach Einwohnerzahl (kleinste zuerst, 2023).",
      items: [
        { id: "A", label: "Indien (~1,4 Mrd.)" },
        { id: "B", label: "USA (~330 Mio.)" },
        { id: "C", label: "Deutschland (~84 Mio.)" },
        { id: "D", label: "China (~1,4 Mrd.)" },
      ],
      correctOrder: ["C", "B", "D", "A"],
      durationMs: 25_000,
      points: 5,
    },
    {
      id: "q-rank-17",
      type: QuestionType.Ranking,
      text: "Sortiere diese Snacks nach Kalorien pro 100g (wenigste zuerst).",
      items: [
        { id: "A", label: "Pringles (~521 kcal)" },
        { id: "B", label: "Haribo Goldbären (~340 kcal)" },
        { id: "C", label: "Milka Schokolade (~530 kcal)" },
        { id: "D", label: "Nutella (~539 kcal)" },
      ],
      correctOrder: ["B", "A", "C", "D"],
      durationMs: 25_000,
      points: 5,
    },
    {
      id: "q-rank-18",
      type: QuestionType.Ranking,
      text: "Sortiere diese Musikgenres nach deutschem Streaming-Anteil (kleinster zuerst, 2022).",
      items: [
        { id: "A", label: "Deutschrap (~32%)" },
        { id: "B", label: "Klassik (~3%)" },
        { id: "C", label: "Pop (~28%)" },
        { id: "D", label: "Rock (~15%)" },
      ],
      correctOrder: ["B", "D", "C", "A"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-19",
      type: QuestionType.Ranking,
      text: "Sortiere diese deutschen Bundesländer nach Fläche (kleinste zuerst).",
      items: [
        { id: "A", label: "Bayern" },
        { id: "B", label: "Bremen" },
        { id: "C", label: "Nordrhein-Westfalen" },
        { id: "D", label: "Sachsen" },
      ],
      correctOrder: ["B", "D", "C", "A"],
      durationMs: 25_000,
      points: 5,
    },
    {
      id: "q-rank-20",
      type: QuestionType.Ranking,
      text: "Sortiere diese Videospiele nach Erscheinungsjahr (ältestes zuerst).",
      items: [
        { id: "A", label: "The Sims (2000)" },
        { id: "B", label: "GTA Vice City (2002)" },
        { id: "C", label: "Minecraft (2011, PC-Launch)" },
        { id: "D", label: "World of Warcraft (2004)" },
      ],
      correctOrder: ["A", "B", "D", "C"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-21",
      type: QuestionType.Ranking,
      text: "Sortiere diese Kaffeespezialitäten nach Koffeingehalt (wenigste zuerst).",
      items: [
        { id: "A", label: "Espresso (~63 mg pro Schuss)" },
        { id: "B", label: "Filterkaffee (~95 mg/200ml)" },
        { id: "C", label: "Entkoffeinierter Kaffee (~2 mg)" },
        { id: "D", label: "Red Bull (~80 mg/250ml)" },
      ],
      correctOrder: ["C", "A", "D", "B"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-22",
      type: QuestionType.Ranking,
      text: "Sortiere diese Serien nach Erscheinungsjahr der ersten Episode (älteste zuerst).",
      items: [
        { id: "A", label: "Breaking Bad (2008)" },
        { id: "B", label: "The Office US (2005)" },
        { id: "C", label: "Stranger Things (2016)" },
        { id: "D", label: "Game of Thrones (2011)" },
      ],
      correctOrder: ["B", "A", "D", "C"],
      durationMs: 30_000,
      points: 5,
    },
    {
      id: "q-rank-23",
      type: QuestionType.Ranking,
      text: "Sortiere diese iPhone-Modelle nach Erscheinungsjahr (ältestes zuerst).",
      items: [
        { id: "A", label: "iPhone 5 (2012)" },
        { id: "B", label: "iPhone 3G (2008)" },
        { id: "C", label: "iPhone X (2017)" },
        { id: "D", label: "iPhone 12 (2020)" },
      ],
      correctOrder: ["B", "A", "C", "D"],
      durationMs: 25_000,
      points: 5,
    },
    {
      id: "q-rank-24",
      type: QuestionType.Ranking,
      text: "Sortiere diese Jahrzehnte nach deutschem Geburtenrate (höchste zuerst).",
      items: [
        { id: "A", label: "1960er" },
        { id: "B", label: "1980er" },
        { id: "C", label: "2000er" },
        { id: "D", label: "2020er" },
      ],
      correctOrder: ["A", "B", "C", "D"],
      durationMs: 30_000,
      points: 5,
    },
    {
      id: "q-rank-25",
      type: QuestionType.Ranking,
      text: "Sortiere diese Sportarten nach Anzahl der Mitglieder in deutschen Vereinen (wenigste zuerst, 2022).",
      items: [
        { id: "A", label: "Turnen (~4,6 Mio.)" },
        { id: "B", label: "Tennis (~1,4 Mio.)" },
        { id: "C", label: "Fußball (~6,7 Mio.)" },
        { id: "D", label: "Handball (~0,8 Mio.)" },
      ],
      correctOrder: ["D", "B", "A", "C"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-26",
      type: QuestionType.Ranking,
      text: "Sortiere diese deutschen Schlagzeilen-Ereignisse chronologisch (ältestes zuerst).",
      items: [
        { id: "A", label: "Facebook-Gründung (2004)" },
        { id: "B", label: "Mauerfall (1989)" },
        { id: "C", label: "iPhone-Launch in Deutschland (2007)" },
        { id: "D", label: "Euro-Einführung als Bargeld (2002)" },
      ],
      correctOrder: ["B", "A", "D", "C"],
      durationMs: 30_000,
      points: 5,
    },
    {
      id: "q-rank-27",
      type: QuestionType.Ranking,
      text: "Sortiere diese Länder nach ihrer Landfläche (kleinste zuerst).",
      items: [
        { id: "A", label: "Russland" },
        { id: "B", label: "Deutschland" },
        { id: "C", label: "Australien" },
        { id: "D", label: "Kanada" },
      ],
      correctOrder: ["B", "C", "D", "A"],
      durationMs: 25_000,
      points: 5,
    },
    {
      id: "q-rank-28",
      type: QuestionType.Ranking,
      text: "Sortiere diese Emojis nach Erscheinungsjahr als offizieller Unicode-Standard (älteste zuerst).",
      items: [
        { id: "A", label: "💀 (2010)" },
        { id: "B", label: "🥑 (2016)" },
        { id: "C", label: "😂 (2010)" },
        { id: "D", label: "🫠 (2021)" },
      ],
      correctOrder: ["A", "C", "B", "D"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-29",
      type: QuestionType.Ranking,
      text: "Sortiere diese deutschen Wörter nach Buchstabenanzahl (kürzeste zuerst).",
      items: [
        { id: "A", label: "Rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz (63)" },
        { id: "B", label: "Donaudampfschifffahrtsgesellschaft (34)" },
        { id: "C", label: "Kraftfahrzeug (13)" },
        { id: "D", label: "Rechtsschutzversicherungsgesellschaften (36)" },
      ],
      correctOrder: ["C", "B", "D", "A"],
      durationMs: 30_000,
      points: 5,
    },
    {
      id: "q-rank-30",
      type: QuestionType.Ranking,
      text: "Sortiere diese Cocktails nach ungefährem Alkoholgehalt (niedrigster zuerst).",
      items: [
        { id: "A", label: "Long Island Iced Tea (~22%)" },
        { id: "B", label: "Radler (~2,5%)" },
        { id: "C", label: "Mojito (~10%)" },
        { id: "D", label: "Aperol Spritz (~8%)" },
      ],
      correctOrder: ["B", "D", "C", "A"],
      durationMs: 25_000,
      points: 6,
    },
    {
      id: "q-rank-31",
      type: QuestionType.Ranking,
      text: "Sortiere diese YouTube-Kanäle nach Anzahl der Subscriber (wenigste zuerst, ca. 2024).",
      items: [
        { id: "A", label: "MrBeast (~300 Mio.)" },
        { id: "B", label: "PewDiePie (~111 Mio.)" },
        { id: "C", label: "T-Series (~270 Mio.)" },
        { id: "D", label: "Cocomelon (~175 Mio.)" },
      ],
      correctOrder: ["B", "D", "C", "A"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-32",
      type: QuestionType.Ranking,
      text: "Sortiere diese deutschen Autobahnen nach ihrer Länge (kürzeste zuerst).",
      items: [
        { id: "A", label: "A3 (~775 km)" },
        { id: "B", label: "A7 (~963 km, längste Deutschlands)" },
        { id: "C", label: "A1 (~742 km)" },
        { id: "D", label: "A9 (~530 km)" },
      ],
      correctOrder: ["D", "C", "A", "B"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-33",
      type: QuestionType.Ranking,
      text: "Sortiere diese Weltrekorde nach Zahl (kleinste zuerst).",
      items: [
        { id: "A", label: "Höchster Berg der Welt in m (8.849)" },
        { id: "B", label: "Tiefste Meeresgraben in m (11.034)" },
        { id: "C", label: "Schnellster Mensch (100m in s: 9,58)" },
        { id: "D", label: "Ältester Mensch je (Lebensjahre: 122)" },
      ],
      correctOrder: ["C", "D", "A", "B"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-34",
      type: QuestionType.Ranking,
      text: "Sortiere diese Krankheiten nach Häufigkeit als Todesursache in Deutschland (seltenste zuerst, 2022).",
      items: [
        { id: "A", label: "Herzkreislauf-Erkrankungen (~35% aller Todesfälle)" },
        { id: "B", label: "Krebs (~25%)" },
        { id: "C", label: "Atemwegserkrankungen (~6%)" },
        { id: "D", label: "Demenz (~8%)" },
      ],
      correctOrder: ["C", "D", "B", "A"],
      durationMs: 30_000,
      points: 6,
    },
    {
      id: "q-rank-35",
      type: QuestionType.Ranking,
      text: "Sortiere diese Millennials-Symbole nach Erscheinungsjahr (ältestes zuerst).",
      items: [
        { id: "A", label: "Beyblade (1999)" },
        { id: "B", label: "Tamagotchi (1996)" },
        { id: "C", label: "Bratz-Puppen (2001)" },
        { id: "D", label: "Webkinz (2005)" },
      ],
      correctOrder: ["B", "A", "C", "D"],
      durationMs: 30_000,
      points: 6,
    },

    // ─── LOGIK- UND ÜBERRASCHUNGSFRAGEN (logic) ────────────────────────────────

    {
      id: "q-logic-01",
      type: QuestionType.Logic,
      text: "Ein Arzt gibt dir 3 Pillen und sagt: 'Nimm eine alle halbe Stunde.' Wann hast du alle Pillen genommen?",
      options: [
        { id: "A", label: "Nach 1,5 Stunden" },
        { id: "B", label: "Nach 1 Stunde" },
        { id: "C", label: "Nach 45 Minuten" },
        { id: "D", label: "Nach 2 Stunden" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-logic-02",
      type: QuestionType.Logic,
      text: "Welches Land hat die meisten Seen der Welt – mehr als alle anderen Länder zusammen?",
      options: [
        { id: "A", label: "Russland" },
        { id: "B", label: "Finnland" },
        { id: "C", label: "Kanada" },
        { id: "D", label: "Norwegen" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-logic-03",
      type: QuestionType.Logic,
      text: "Was verkaufte sich bis 2012 weltweit am meisten – und ist auch heute noch eines der meistverkauften Videospiele aller Zeiten?",
      options: [
        { id: "A", label: "Tetris" },
        { id: "B", label: "Super Mario Bros." },
        { id: "C", label: "Minecraft" },
        { id: "D", label: "GTA V" },
      ],
      correctOptionId: "A",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-logic-04",
      type: QuestionType.Logic,
      text: "Du überholst den Zweiten in einem Rennen. Auf welchem Platz bist du jetzt?",
      options: [
        { id: "A", label: "Erster" },
        { id: "B", label: "Zweiter" },
        { id: "C", label: "Dritter" },
        { id: "D", label: "Kommt drauf an" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 3,
    },
    {
      id: "q-logic-05",
      type: QuestionType.Logic,
      text: "Welches Tier ist kein Insekt?",
      options: [
        { id: "A", label: "Ameise" },
        { id: "B", label: "Spinne" },
        { id: "C", label: "Käfer" },
        { id: "D", label: "Schmetterling" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 3,
    },
    {
      id: "q-logic-06",
      type: QuestionType.Logic,
      text: "Was passiert mit dem Leergewicht eines Flugzeugs, wenn es tankt – bevor es startet?",
      options: [
        { id: "A", label: "Es bleibt gleich" },
        { id: "B", label: "Es wird schwerer" },
        { id: "C", label: "Es wird leichter" },
        { id: "D", label: "Leergewicht ändert sich nicht" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-logic-07",
      type: QuestionType.Logic,
      text: "Welche Farbe hat ein Spiegel wirklich, wenn man ihn ganz genau anschaut?",
      options: [
        { id: "A", label: "Silber" },
        { id: "B", label: "Weiß" },
        { id: "C", label: "Grün" },
        { id: "D", label: "Keine Farbe, er reflektiert nur" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-logic-08",
      type: QuestionType.Logic,
      text: "Wieviele Länder gibt es offiziell auf der Erde?",
      options: [
        { id: "A", label: "195" },
        { id: "B", label: "204" },
        { id: "C", label: "178" },
        { id: "D", label: "212" },
      ],
      correctOptionId: "A",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-logic-09",
      type: QuestionType.Logic,
      text: "Wie viele Monate haben 28 Tage?",
      options: [
        { id: "A", label: "Nur der Februar" },
        { id: "B", label: "Alle 12" },
        { id: "C", label: "1 oder 2, je nach Schaltjahr" },
        { id: "D", label: "4 Monate" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 3,
    },
    {
      id: "q-logic-10",
      type: QuestionType.Logic,
      text: "Ein Bauer hat 17 Schafe. Alle bis auf 9 sterben. Wie viele Schafe hat er noch?",
      options: [
        { id: "A", label: "8" },
        { id: "B", label: "17" },
        { id: "C", label: "9" },
        { id: "D", label: "0" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 3,
    },
    {
      id: "q-logic-11",
      type: QuestionType.Logic,
      text: "Welches Land grenzt an die meisten anderen Länder?",
      options: [
        { id: "A", label: "China (14 Nachbarn)" },
        { id: "B", label: "Russland (14 Nachbarn)" },
        { id: "C", label: "Brasilien (10 Nachbarn)" },
        { id: "D", label: "Beide: China und Russland teilen sich Platz 1" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-logic-12",
      type: QuestionType.Logic,
      text: "Wenn du einen 10-Euro-Schein in zwei gleiche Teile reißt – was hast du dann?",
      options: [
        { id: "A", label: "Zwei Scheine à 5 Euro" },
        { id: "B", label: "Nichts Wertvolles mehr" },
        { id: "C", label: "Immer noch 10 Euro, solange die Seriennummer erkennbar ist" },
        { id: "D", label: "5 Euro Schadensersatz-Anspruch" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-logic-13",
      type: QuestionType.Logic,
      text: "Was ist das meistverwendete Passwort der Welt?",
      options: [
        { id: "A", label: "123456" },
        { id: "B", label: "password" },
        { id: "C", label: "qwerty" },
        { id: "D", label: "iloveyou" },
      ],
      correctOptionId: "A",
      durationMs: 15_000,
      points: 3,
    },
    {
      id: "q-logic-14",
      type: QuestionType.Logic,
      text: "Welche Farbe hat Coca-Cola, wenn man den roten Farbstoff weglässt?",
      options: [
        { id: "A", label: "Dunkelbraun" },
        { id: "B", label: "Grünlich" },
        { id: "C", label: "Hellgelb bis farblos" },
        { id: "D", label: "Schwarz" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-logic-15",
      type: QuestionType.Logic,
      text: "Wie viele Beine hat eine Biene?",
      options: [
        { id: "A", label: "4" },
        { id: "B", label: "6" },
        { id: "C", label: "8" },
        { id: "D", label: "12" },
      ],
      correctOptionId: "B",
      durationMs: 12_000,
      points: 2,
    },
    {
      id: "q-logic-16",
      type: QuestionType.Logic,
      text: "Was liegt näher an der Erde: der Mond oder die Internationale Raumstation (ISS)?",
      options: [
        { id: "A", label: "Der Mond (~384.000 km)" },
        { id: "B", label: "Die ISS (~400 km)" },
        { id: "C", label: "Beide gleich weit" },
        { id: "D", label: "Kommt auf den Tag an" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 3,
    },
    {
      id: "q-logic-17",
      type: QuestionType.Logic,
      text: "In welcher deutschen Stadt steht der Kölner Dom?",
      options: [
        { id: "A", label: "Düsseldorf" },
        { id: "B", label: "Köln" },
        { id: "C", label: "Aachen" },
        { id: "D", label: "Bonn" },
      ],
      correctOptionId: "B",
      durationMs: 8_000,
      points: 1,
    },
    {
      id: "q-logic-18",
      type: QuestionType.Logic,
      text: "Was ist die häufigste Todesursache bei unter-30-Jährigen in Deutschland?",
      options: [
        { id: "A", label: "Krebs" },
        { id: "B", label: "Herzinfarkt" },
        { id: "C", label: "Unfall" },
        { id: "D", label: "Suizid" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-logic-19",
      type: QuestionType.Logic,
      text: "Wenn ein Flugzeug 400 km/h über dem Boden fliegt und der Wind entgegenkommt mit 100 km/h – wie schnell ist das Flugzeug über dem Boden?",
      options: [
        { id: "A", label: "500 km/h" },
        { id: "B", label: "400 km/h" },
        { id: "C", label: "300 km/h" },
        { id: "D", label: "Das Flugzeug steht" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-logic-20",
      type: QuestionType.Logic,
      text: "Was wiegt mehr: ein Kilogramm Federn oder ein Kilogramm Stahl?",
      options: [
        { id: "A", label: "Ein Kilogramm Stahl" },
        { id: "B", label: "Ein Kilogramm Federn" },
        { id: "C", label: "Beide gleich viel" },
        { id: "D", label: "Kommt auf die Federn an" },
      ],
      correctOptionId: "C",
      durationMs: 10_000,
      points: 2,
    },
    {
      id: "q-logic-21",
      type: QuestionType.Logic,
      text: "Welcher Teil des menschlichen Körpers wächst ein Leben lang?",
      options: [
        { id: "A", label: "Haare und Nägel" },
        { id: "B", label: "Ohren und Nase" },
        { id: "C", label: "Zähne" },
        { id: "D", label: "Finger" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-logic-22",
      type: QuestionType.Logic,
      text: "Welches Land hatte zuerst Frauen-Wahlrecht?",
      options: [
        { id: "A", label: "Deutschland (1918)" },
        { id: "B", label: "Neuseeland (1893)" },
        { id: "C", label: "Schweden (1921)" },
        { id: "D", label: "USA (1920)" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-logic-23",
      type: QuestionType.Logic,
      text: "Was ist das berühmteste Gemälde der Welt – und in welchem Museum hängt es?",
      options: [
        { id: "A", label: "Die Erschaffung Adams – Vatikan" },
        { id: "B", label: "Mona Lisa – Louvre, Paris" },
        { id: "C", label: "Das Letzte Abendmahl – Mailand" },
        { id: "D", label: "Sternennacht – MoMA, New York" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 3,
    },
    {
      id: "q-logic-24",
      type: QuestionType.Logic,
      text: "Wofür steht das 'www' in einer Webadresse?",
      options: [
        { id: "A", label: "World Wide Web" },
        { id: "B", label: "Wireless Wide Wavelength" },
        { id: "C", label: "Web Worldwide Works" },
        { id: "D", label: "World Web Wires" },
      ],
      correctOptionId: "A",
      durationMs: 12_000,
      points: 2,
    },
    {
      id: "q-logic-25",
      type: QuestionType.Logic,
      text: "Warum haben Piraten in Filmen immer eine Augenklappe?",
      options: [
        { id: "A", label: "Wegen häufiger Verletzungen auf See" },
        { id: "B", label: "Um unter Deck schneller an die Dunkelheit gewöhnt zu sein" },
        { id: "C", label: "Es war ein Modetrend im 18. Jahrhundert" },
        { id: "D", label: "Augenklappe war Statussymbol für erfahrene Seefahrer" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-logic-26",
      type: QuestionType.Logic,
      text: "Welches Land hat zuerst das Internet erfunden (bzw. ARPANET entwickelt)?",
      options: [
        { id: "A", label: "Japan" },
        { id: "B", label: "Großbritannien" },
        { id: "C", label: "USA" },
        { id: "D", label: "Deutschland" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 3,
    },
    {
      id: "q-logic-27",
      type: QuestionType.Logic,
      text: "Was haben Haie und Elefanten gemeinsam, das die meisten Menschen nicht wissen?",
      options: [
        { id: "A", label: "Sie haben beide drei Herzkammern" },
        { id: "B", label: "Beide können Krebs bekommen" },
        { id: "C", label: "Beide schlafen nie tief" },
        { id: "D", label: "Beide haben kein Knochenmark" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-logic-28",
      type: QuestionType.Logic,
      text: "Welcher berühmte Satz wird Albert Einstein oft zugeschrieben, obwohl er ihn nie gesagt hat?",
      options: [
        { id: "A", label: '"Gott würfelt nicht."' },
        {
          id: "B",
          label:
            '"Die Definition von Wahnsinn ist, immer dasselbe zu tun und andere Ergebnisse zu erwarten."',
        },
        {
          id: "C",
          label: '"Zwei Dinge sind unendlich: das Universum und die menschliche Dummheit."',
        },
        { id: "D", label: '"E = mc²"' },
      ],
      correctOptionId: "B",
      durationMs: 25_000,
      points: 5,
    },
    {
      id: "q-logic-29",
      type: QuestionType.Logic,
      text: "Was ist keine tatsächliche Funktion von Eyebrows?",
      options: [
        { id: "A", label: "Schweiß vom Auge ableiten" },
        { id: "B", label: "Emotionen ausdrücken" },
        { id: "C", label: "Andere Personen identifizieren" },
        { id: "D", label: "UV-Schutz für die Augen" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-logic-30",
      type: QuestionType.Logic,
      text: "Welches Land hat die meisten UNESCO-Welterbestätten?",
      options: [
        { id: "A", label: "China" },
        { id: "B", label: "Frankreich" },
        { id: "C", label: "Italien" },
        { id: "D", label: "Deutschland" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-logic-31",
      type: QuestionType.Logic,
      text: "Was ist die häufigste Ursache für Hausbrände in Deutschland?",
      options: [
        { id: "A", label: "Kerzen" },
        { id: "B", label: "Elektrische Geräte" },
        { id: "C", label: "Kochen/Herd vergessen" },
        { id: "D", label: "Zigaretten" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-logic-32",
      type: QuestionType.Logic,
      text: "Wer war nach Angela Merkel die erste Bundeskanzlerin Deutschlands?",
      options: [
        { id: "A", label: "Annalena Baerbock" },
        { id: "B", label: "Ursula von der Leyen" },
        { id: "C", label: "Saskia Esken" },
        {
          id: "D",
          label: "Es gibt noch keine zweite Bundeskanzlerin – aktuell ist ein Mann im Amt",
        },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-logic-33",
      type: QuestionType.Logic,
      text: "Welches Tier schläft am wenigsten von allen Säugetieren?",
      options: [
        { id: "A", label: "Elefant (~2 Stunden/Tag)" },
        { id: "B", label: "Giraffe (~0,5 Stunden/Tag)" },
        { id: "C", label: "Pferd (~3 Stunden/Tag)" },
        { id: "D", label: "Delfin (~8 Stunden, aber abwechselnd)" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-logic-34",
      type: QuestionType.Logic,
      text: "Was passiert, wenn du in einem schwebenden Aufzug springst?",
      options: [
        { id: "A", label: "Du landest an der Decke" },
        { id: "B", label: "Du fällst durch – physikalisch unmöglich zu springen" },
        { id: "C", label: "Du fällst mit dem Aufzug, dein Sprung verändert nichts" },
        { id: "D", label: "Der Aufzug bewegt sich durch deinen Absprung nach unten" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-logic-35",
      type: QuestionType.Logic,
      text: "Was ist in Deutschland laut Gesetz bei einem Autounfall Pflicht?",
      options: [
        { id: "A", label: "Fotos machen, bevor man aussteigt" },
        { id: "B", label: "Warndreieck aufstellen, Warnweste anziehen, Erste Hilfe leisten" },
        { id: "C", label: "Polizei immer sofort anrufen" },
        { id: "D", label: "Fahrzeug auf die Seite fahren – egal wie" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-logic-36",
      type: QuestionType.Logic,
      text: "Was ist der häufigste Fehler beim Zähneputzen?",
      options: [
        { id: "A", label: "Zu selten putzen" },
        { id: "B", label: "Zu kurz putzen (unter 2 Minuten)" },
        { id: "C", label: "Mit zu hartem Druck putzen" },
        { id: "D", label: "Falsche Zahnpasta verwenden" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-logic-37",
      type: QuestionType.Logic,
      text: "Warum schmeckt Saft nach einer Reise zum Zahnarzt komisch?",
      options: [
        { id: "A", label: "Das Betäubungsmittel betäubt auch die Geschmacksnerven" },
        { id: "B", label: "Die Fluoridbehandlung verändert den Speichel" },
        { id: "C", label: "Zahnpasta-Reste neutralisieren die Süße" },
        { id: "D", label: "Stress verändert die Geschmackswahrnehmung" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 5,
    },
    {
      id: "q-logic-38",
      type: QuestionType.Logic,
      text: "Welches Tier ist für die meisten Menschentode pro Jahr verantwortlich?",
      options: [
        { id: "A", label: "Löwe" },
        { id: "B", label: "Nilpferd" },
        { id: "C", label: "Mücke" },
        { id: "D", label: "Schlange" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 4,
    },
    {
      id: "q-logic-39",
      type: QuestionType.Logic,
      text: "Was wächst schneller: Fingernägel oder Zehennägel?",
      options: [
        { id: "A", label: "Zehennägel" },
        { id: "B", label: "Fingernägel" },
        { id: "C", label: "Beide gleich schnell" },
        { id: "D", label: "Kommt auf das Alter an" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 3,
    },
    {
      id: "q-logic-40",
      type: QuestionType.Logic,
      text: "Welcher Bundeskanzler war am längsten im Amt?",
      options: [
        { id: "A", label: "Helmut Schmidt" },
        { id: "B", label: "Willy Brandt" },
        { id: "C", label: "Angela Merkel" },
        { id: "D", label: "Helmut Kohl" },
      ],
      correctOptionId: "D",
      durationMs: 15_000,
      points: 3,
    },
  ],
};

export function getDefaultQuiz(): Quiz {
  return MILLENNIALS_QUIZ;
}
