import { QuestionType, type Quiz } from "@quiz/shared-types";

const MILLENNIALS_QUIZ: Quiz = {
  id: "millennials-quiz-001",
  title: "Millennials-Quiz",
  questions: [
    // Harry Potter
    {
      id: "q-hp-01",
      type: QuestionType.MultipleChoice,
      text: "Wie lautet das erste Gryffindor-Passwort im ersten Harry-Potter-Film?",
      options: [
        { id: "A", label: "Caput Draconis" },
        { id: "B", label: "Wingardium Leviosa" },
        { id: "C", label: "Lumos Solem" },
        { id: "D", label: "Ohrenschmalz" },
      ],
      correctOptionId: "A",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-hp-02",
      type: QuestionType.MultipleChoice,
      text: "Welches Körperteil bricht Harry sich beim Quidditch-Spiel in 'Die Kammer des Schreckens', bevor Lockhart hilft?",
      options: [
        { id: "A", label: "Den linken Arm" },
        { id: "B", label: "Den rechten Arm" },
        { id: "C", label: "Das Schlüsselbein" },
        { id: "D", label: "Das Handgelenk" },
      ],
      correctOptionId: "B",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-hp-03",
      type: QuestionType.MultipleChoice,
      text: "Welchen Drachen bekommt Harry in der ersten Aufgabe des Trimagischen Turniers?",
      options: [
        { id: "A", label: "Den chinesischen Feuerball" },
        { id: "B", label: "Den walisischen Grünschwanz" },
        { id: "C", label: "Den schwedischen Kurzschnauzer" },
        { id: "D", label: "Den ungarischen Hornschwanz" },
      ],
      correctOptionId: "D",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-hp-04",
      type: QuestionType.MultipleChoice,
      text: "Wie heißt das Magazin, das Xenophilius Lovegood herausgibt?",
      options: [
        { id: "A", label: "Der Klitterer" },
        { id: "B", label: "Der Tagesprophet" },
        { id: "C", label: "Hexenwoche" },
        { id: "D", label: "Der Abendprophet" },
      ],
      correctOptionId: "A",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-hp-05",
      type: QuestionType.MultipleChoice,
      text: "Welches Tier erscheint patronusförmig bei Snapes Nachricht an Harry im Wald?",
      options: [
        { id: "A", label: "Ein Hirsch" },
        { id: "B", label: "Eine Hirschkuh" },
        { id: "C", label: "Ein Otter" },
        { id: "D", label: "Ein Wolf" },
      ],
      correctOptionId: "B",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-hp-06",
      type: QuestionType.MultipleChoice,
      text: "Wie heißt der Zauberspruch, mit dem Harry Draco im sechsten Film schwer verletzt?",
      options: [
        { id: "A", label: "Crucio" },
        { id: "B", label: "Expelliarmus" },
        { id: "C", label: "Sectumsempra" },
        { id: "D", label: "Avada Kedavra" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-hp-07",
      type: QuestionType.MultipleChoice,
      text: "Welchen Zauberspruch benutzt Hermine im ersten Film, um die Teufelsschlinge zu besiegen?",
      options: [
        { id: "A", label: "Alohomora" },
        { id: "B", label: "Expecto Patronum" },
        { id: "C", label: "Lumos Solem" },
        { id: "D", label: "Reparo" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-hp-08",
      type: QuestionType.MultipleChoice,
      text: "Wie viele unverzeihliche Flüche nennt Professor Moody im vierten Harry-Potter-Film?",
      options: [
        { id: "A", label: "Zwei" },
        { id: "B", label: "Drei" },
        { id: "C", label: "Fünf" },
        { id: "D", label: "Sieben" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-hp-09",
      type: QuestionType.MultipleChoice,
      text: "Wie lautet der zweite Vorname von Harry Potter?",
      options: [
        { id: "A", label: "Thomas" },
        { id: "B", label: "George" },
        { id: "C", label: "James" },
        { id: "D", label: "William" },
      ],
      correctOptionId: "C",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-hp-10",
      type: QuestionType.MultipleChoice,
      text: "Wie heißt der dreiköpfige Hund, der im ersten Film die Falltür bewacht?",
      options: [
        { id: "A", label: "Cerberus" },
        { id: "B", label: "Fluffy" },
        { id: "C", label: "Bruno" },
        { id: "D", label: "Kralle" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-hp-11",
      type: QuestionType.MultipleChoice,
      text: "Welche weltbekannte Schauspielerin wurde für die Rolle der Helena Ravenclaw angefragt, bevor Kelly Macdonald sie spielte?",
      options: [
        { id: "A", label: "Keira Knightley" },
        { id: "B", label: "Cate Blanchett" },
        { id: "C", label: "Emma Thompson" },
        { id: "D", label: "Kate Winslet" },
      ],
      correctOptionId: "D",
      durationMs: 12_000,
      points: 3,
    },
    // Millennial-Slang & Internet-Fossilien
    {
      id: "q-sl-01",
      type: QuestionType.MultipleChoice,
      text: "Welches Geräusch machte ICQ bei einer neuen Nachricht?",
      options: [
        { id: "A", label: "Ein Ping" },
        { id: "B", label: "Ein Glöckchen" },
        { id: "C", label: "Uh-oh!" },
        { id: "D", label: "Ein Klopfen" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sl-02",
      type: QuestionType.MultipleChoice,
      text: "Welches deutsche soziale Netzwerk war für Schüler prägendster Treffpunkt vor Facebook?",
      options: [
        { id: "A", label: "MySpace" },
        { id: "B", label: "Xing" },
        { id: "C", label: "Studi17" },
        { id: "D", label: "SchülerVZ" },
      ],
      correctOptionId: "D",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-sl-03",
      type: QuestionType.MultipleChoice,
      text: "Was war 'gruscheln' bei StudiVZ?",
      options: [
        { id: "A", label: "Eine Funktion zum Teilen von Fotos" },
        { id: "B", label: "Ein Spiel im Netzwerk" },
        { id: "C", label: "Das Schreiben öffentlicher Pinnwand-Posts" },
        { id: "D", label: "Mischung aus grüßen und kuscheln – digitaler Fremdschamkontakt" },
      ],
      correctOptionId: "D",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-sl-04",
      type: QuestionType.MultipleChoice,
      text: "Welche Schriftart galt in Kettenbriefen und peinlichen Profilen als Pflicht-Klischee?",
      options: [
        { id: "A", label: "Arial" },
        { id: "B", label: "Comic Sans" },
        { id: "C", label: "Papyrus" },
        { id: "D", label: "Times New Roman" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sl-05",
      type: QuestionType.MultipleChoice,
      text: "Was war mit 'ASL?' in alten Chats gemeint?",
      options: [
        { id: "A", label: "Account, Status, Link" },
        { id: "B", label: "Age, Sex, Location" },
        { id: "C", label: "Always Stay Logged-in" },
        { id: "D", label: "Assigned Screen Language" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-sl-06",
      type: QuestionType.MultipleChoice,
      text: "Was war der 'Nudge' bei MSN Messenger?",
      options: [
        { id: "A", label: "Eine Möglichkeit, Bilder direkt zu teilen" },
        { id: "B", label: "Eine Funktion, die das Chatfenster des Gegenübers schüttelte" },
        { id: "C", label: "Der Offline-Status-Sound" },
        { id: "D", label: "Eine animierte Freundschaftsanfrage" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-sl-07",
      type: QuestionType.MultipleChoice,
      text: "Wofür stand 'brb' in alten Chats?",
      options: [
        { id: "A", label: "Back room buddy" },
        { id: "B", label: "Bring real beer" },
        { id: "C", label: "Be right back" },
        { id: "D", label: "Be really bored" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sl-08",
      type: QuestionType.MultipleChoice,
      text: "Was bedeutet 'YOLO'?",
      options: [
        { id: "A", label: "Your online life online" },
        { id: "B", label: "You only live once" },
        { id: "C", label: "You obviously love others" },
        { id: "D", label: "You owe, live on" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sl-09",
      type: QuestionType.MultipleChoice,
      text: "Wofür nutzte man '404' als Witz im Netzjargon?",
      options: [
        { id: "A", label: "Dass jemand offline gegangen ist" },
        { id: "B", label: "Dass jemand im Forum gesperrt wurde" },
        { id: "C", label: "Dass jemand nichts kapiert oder nicht gefunden wird" },
        { id: "D", label: "Dass jemand verliebt ist" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-sl-10",
      type: QuestionType.MultipleChoice,
      text: "Was war '1337' bzw. 'leet' im Internet-Jargon?",
      options: [
        { id: "A", label: "Ein Elite-Gaming-Clan-Präfix" },
        { id: "B", label: "Eine Hacker-/Gamer-Schreibweise mit Zahlen statt Buchstaben" },
        { id: "C", label: "Ein Modding-Tool für PC-Spiele" },
        { id: "D", label: "Ein Cheat-Code für Counter-Strike" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    // Dating-Slang & Beziehungs-Bullshit
    {
      id: "q-ds-01",
      type: QuestionType.MultipleChoice,
      text: "Was bedeutet 'Netflix & Chill' im Internet-Slang meistens wirklich?",
      options: [
        { id: "A", label: "Gemeinsam entspannt eine Serie bingen" },
        { id: "B", label: "Den Abend mit Popcorn und Film verbringen" },
        { id: "C", label: "Sexuelle oder romantische Annäherung statt Serien schauen" },
        { id: "D", label: "Ungestört vom Partner Videospiele spielen" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-ds-02",
      type: QuestionType.MultipleChoice,
      text: "Wofür steht 'ghosting' beim Dating?",
      options: [
        { id: "A", label: "Heimliches Stalken über Social Media" },
        { id: "B", label: "Plötzlicher Kontaktabbruch ohne Erklärung" },
        { id: "C", label: "Das Versenden anonymer Nachrichten" },
        { id: "D", label: "Jemanden auf allen Plattformen blockieren" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-ds-03",
      type: QuestionType.MultipleChoice,
      text: "Was meint 'catfishing'?",
      options: [
        { id: "A", label: "Das anonyme Verbreiten von Gerüchten im Netz" },
        { id: "B", label: "Eine Dating-App speziell für Outdoor-Fans" },
        { id: "C", label: "Freunde ungefragt in Fotos taggen" },
        {
          id: "D",
          label: "Jemand gibt online eine falsche Identität vor, oft romantisch/manipulativ",
        },
      ],
      correctOptionId: "D",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-ds-04",
      type: QuestionType.MultipleChoice,
      text: "Was meint 'love bombing'?",
      options: [
        { id: "A", label: "Das gleichzeitige Daten mehrerer Personen" },
        { id: "B", label: "Übermäßige Zuwendung am Anfang einer Beziehung, oft manipulativ" },
        { id: "C", label: "Eine Strategie, bei der man absichtlich kalt bleibt" },
        { id: "D", label: "Unangemessen anzügliche Direktnachrichten schicken" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-ds-05",
      type: QuestionType.MultipleChoice,
      text: "Was bedeutet 'NSFW'?",
      options: [
        { id: "A", label: "New Social Feed Weekly" },
        { id: "B", label: "No Sharing For Women" },
        { id: "C", label: "Not Safe For Work" },
        { id: "D", label: "Need Some Fun Words" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-ds-06",
      type: QuestionType.MultipleChoice,
      text: "Was bezeichnet 'situationship'?",
      options: [
        { id: "A", label: "Eine Fernbeziehung ohne echte Treffen" },
        { id: "B", label: "Eine offene Beziehung mit festem Regelwerk" },
        { id: "C", label: "Eine undefinierte romantisch-sexuelle Verbindung ohne Beziehungslabel" },
        { id: "D", label: "Das gleichzeitige Daten mehrerer Personen" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    // 90er/00er Trash-TV
    {
      id: "q-tv-01",
      type: QuestionType.MultipleChoice,
      text: "Wie hieß das deutsche Dschungelcamp offiziell?",
      options: [
        { id: "A", label: "Überleben im Dschungel" },
        { id: "B", label: "Dschungel der Stars" },
        { id: "C", label: "Wild und Promi" },
        { id: "D", label: "Ich bin ein Star – Holt mich hier raus!" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-tv-02",
      type: QuestionType.MultipleChoice,
      text: "Wie hieß das Jamba-Frosch-Maskottchen mit dem unvergesslichen Klingelton-Song?",
      options: [
        { id: "A", label: "Crazy Frog" },
        { id: "B", label: "Happy Toad" },
        { id: "C", label: "Ringy" },
        { id: "D", label: "Frogster" },
      ],
      correctOptionId: "A",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-tv-03",
      type: QuestionType.MultipleChoice,
      text: "Wie hieß der Jamba-/Jamster-Hase hinter dem berüchtigten Kuschel-Song?",
      options: [
        { id: "A", label: "Sweety" },
        { id: "B", label: "Baby Vuvu" },
        { id: "C", label: "Schnuffel" },
        { id: "D", label: "Husky" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-tv-04",
      type: QuestionType.MultipleChoice,
      text: "Welche legendäre Werbung prägt den Spruch 'Isch abe gar keine Auto'?",
      options: [
        { id: "A", label: "Die Carglass-Werbung" },
        { id: "B", label: "Eine Renault-Clio-Werbung" },
        { id: "C", label: "Die Nescafé-Cappuccino-Werbung mit Angelo" },
        { id: "D", label: "Die Seitenbacher-Werbung" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-tv-05",
      type: QuestionType.MultipleChoice,
      text: "Welche MTV-Show durchleuchtete Schlafzimmer mit UV-Licht, um Dates zu blamieren?",
      options: [
        { id: "A", label: "Next" },
        { id: "B", label: "Parental Control" },
        { id: "C", label: "Room Raiders" },
        { id: "D", label: "Date My Mom" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-tv-06",
      type: QuestionType.MultipleChoice,
      text: "Bei welcher MTV-Dating-Show saß eine Person im Bus und sortierte Kandidaten direkt unterwegs aus?",
      options: [
        { id: "A", label: "Room Raiders" },
        { id: "B", label: "Next" },
        { id: "C", label: "Dismissed" },
        { id: "D", label: "Date My Mom" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-tv-07",
      type: QuestionType.MultipleChoice,
      text: "Welche deutsche Gerichtsshow wurde mit ihrer Titelrichterin zum Nachmittags-Phänomen?",
      options: [
        { id: "A", label: "Richter Alexander Hold" },
        { id: "B", label: "Vera am Mittag" },
        { id: "C", label: "Richterin Barbara Salesch" },
        { id: "D", label: "Das Jugendgericht" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-tv-08",
      type: QuestionType.MultipleChoice,
      text: "Welche ProSieben-Show machte Model-Castings und toxischen Ehrgeiz zum Volkssport?",
      options: [
        { id: "A", label: "Popstars" },
        { id: "B", label: "DSDS" },
        { id: "C", label: "Germany's Next Topmodel" },
        { id: "D", label: "The Voice of Germany" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-tv-09",
      type: QuestionType.MultipleChoice,
      text: "Welcher Sender ließ nachts Zuschauer für offensichtliche Rätsel teures Telefongeld verbrennen?",
      options: [
        { id: "A", label: "DSF" },
        { id: "B", label: "9Live" },
        { id: "C", label: "VIVA" },
        { id: "D", label: "Tele 5" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-tv-10",
      type: QuestionType.MultipleChoice,
      text: "Welche langjährige deutsche Talkshow lief mit Britt Hagedorn?",
      options: [
        { id: "A", label: "Arabella" },
        { id: "B", label: "Vera am Mittag" },
        { id: "C", label: "Britt – Der Talk um eins" },
        { id: "D", label: "TV Total" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-tv-11",
      type: QuestionType.MultipleChoice,
      text: "Wie hieß das penetrant gelbe Jamba-Küken aus der TV-Werbung – nicht Crazy Frog, nicht Schnuffel?",
      options: [
        { id: "A", label: "Chicky" },
        { id: "B", label: "Tweety" },
        { id: "C", label: "Sweety" },
        { id: "D", label: "Froggy" },
      ],
      correctOptionId: "C",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-tv-12",
      type: QuestionType.MultipleChoice,
      text: "Wer war der allererste Dschungelkönig bei 'Ich bin ein Star – Holt mich hier raus!'?",
      options: [
        { id: "A", label: "Désirée Nick" },
        { id: "B", label: "Costa Cordalis" },
        { id: "C", label: "Ross Antony" },
        { id: "D", label: "Ingrid van Bergen" },
      ],
      correctOptionId: "B",
      durationMs: 12_000,
      points: 3,
    },
    // Saufen, Feiern & Jugend-Drinks
    {
      id: "q-dr-01",
      type: QuestionType.MultipleChoice,
      text: "Welcher Alkopop war in den 2000ern das Partygetränk schlechthin in Deutschland?",
      options: [
        { id: "A", label: "Bacardi Breezer" },
        { id: "B", label: "WKD Blue" },
        { id: "C", label: "Desperados" },
        { id: "D", label: "Smirnoff Ice" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-dr-02",
      type: QuestionType.MultipleChoice,
      text: "Woraus besteht ein klassischer Vodka-E?",
      options: [
        { id: "A", label: "Vodka und Limo" },
        { id: "B", label: "Vodka und Energy Drink" },
        { id: "C", label: "Vodka und Tonic" },
        { id: "D", label: "Vodka und Orangensaft" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-dr-03",
      type: QuestionType.MultipleChoice,
      text: "Was bezeichnet 'Vorglühen' im Partykontext?",
      options: [
        { id: "A", label: "Den ersten Tanz des Abends eröffnen" },
        { id: "B", label: "Sich mit Sport vor der Party aufwärmen" },
        { id: "C", label: "Vor dem Ausgehen zuhause oder günstig vortrinken" },
        { id: "D", label: "Die Stimmung mit Musikauswahl aufheizen" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-dr-04",
      type: QuestionType.MultipleChoice,
      text: "Was ist 'Flunkyball'?",
      options: [
        { id: "A", label: "Ein Brettspiel mit Würfeln und Schnapskarten" },
        { id: "B", label: "Ein Volleyball-Trinkspiel für Verlierer" },
        { id: "C", label: "Ein Trinkspiel, bei dem Bälle auf eine Flasche geworfen werden" },
        { id: "D", label: "Ein Dart-Trinkspiel aus den 1990ern" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-dr-05",
      type: QuestionType.MultipleChoice,
      text: "Was bedeutet 'Filmriss' umgangssprachlich?",
      options: [
        { id: "A", label: "Ein Film, der im Kino technisch abbricht" },
        { id: "B", label: "Das Einschlafen beim Film" },
        { id: "C", label: "Ein misslungenes Erlebnis des Abends" },
        { id: "D", label: "Erinnerungslücken durch zu hohen Alkoholkonsum" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-dr-06",
      type: QuestionType.MultipleChoice,
      text: "Was ist ein 'Herrengedeck' im klassischen Kneipenverständnis?",
      options: [
        { id: "A", label: "Bier plus Limo (Diesel)" },
        { id: "B", label: "Bier plus Schnaps" },
        { id: "C", label: "Kaffee mit Schuss" },
        { id: "D", label: "Eine Flasche Wein mit Käsebrett" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-dr-07",
      type: QuestionType.MultipleChoice,
      text: "Woraus besteht ein klassischer Cuba Libre?",
      options: [
        { id: "A", label: "Tequila, Cola und Zitrone" },
        { id: "B", label: "Vodka, Ginger Beer und Limette" },
        { id: "C", label: "Rum, Cola und Limette" },
        { id: "D", label: "Rum, Orangensaft und Grenadine" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    // Absurde Skandale & Popkultur-Meltdowns
    {
      id: "q-sk-01",
      type: QuestionType.MultipleChoice,
      text: "Welche Pop-Ikone rasierte sich 2007 öffentlich den Kopf und wurde damit zur Boulevard-Klischee-Krise?",
      options: [
        { id: "A", label: "Amy Winehouse" },
        { id: "B", label: "Paris Hilton" },
        { id: "C", label: "Britney Spears" },
        { id: "D", label: "Lindsay Lohan" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sk-02",
      type: QuestionType.MultipleChoice,
      text: "Wer riss Taylor Swift bei den MTV VMAs 2009 das Mikrofon weg, um Beyoncé zu loben?",
      options: [
        { id: "A", label: "Chris Brown" },
        { id: "B", label: "Jay-Z" },
        { id: "C", label: "Kanye West" },
        { id: "D", label: "T.I." },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sk-03",
      type: QuestionType.MultipleChoice,
      text: "Welcher Hollywoodstar sprang 2005 in der Oprah-Winfrey-Show auf dem Sofa herum, um seine Liebe zu erklären?",
      options: [
        { id: "A", label: "Will Smith" },
        { id: "B", label: "Tom Cruise" },
        { id: "C", label: "Jim Carrey" },
        { id: "D", label: "Nicolas Cage" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-sk-04",
      type: QuestionType.MultipleChoice,
      text: "Welche Sängerin wurde durch ihren Song 'Rehab' und ihre öffentliche Suchtproblematik zur tragischen Ikone?",
      options: [
        { id: "A", label: "Lily Allen" },
        { id: "B", label: "Adele" },
        { id: "C", label: "Amy Winehouse" },
        { id: "D", label: "Duffy" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-sk-05",
      type: QuestionType.MultipleChoice,
      text: "Welcher Tour-de-France-Sieger wurde zur größten Doping-Schande der 2000er/2010er?",
      options: [
        { id: "A", label: "Jan Ullrich" },
        { id: "B", label: "Marco Pantani" },
        { id: "C", label: "Floyd Landis" },
        { id: "D", label: "Lance Armstrong" },
      ],
      correctOptionId: "D",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-sk-06",
      type: QuestionType.MultipleChoice,
      text: "Mit welchem Tier trat Britney Spears 2001 bei den MTV VMAs auf der Bühne auf?",
      options: [
        { id: "A", label: "Mit einem weißen Tiger" },
        { id: "B", label: "Mit einer Albino-Python" },
        { id: "C", label: "Mit einem Papagei" },
        { id: "D", label: "Mit einem Löwenwelpen" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-sk-07",
      type: QuestionType.MultipleChoice,
      text: "Welcher Schauspieler gab seinem Sohn den bis heute unfassbaren Namen 'Pilot Inspektor'?",
      options: [
        { id: "A", label: "Jason Lee" },
        { id: "B", label: "Nicolas Cage" },
        { id: "C", label: "Bob Geldof" },
        { id: "D", label: "Sylvester Stallone" },
      ],
      correctOptionId: "A",
      durationMs: 12_000,
      points: 3,
    },
    // Gaming
    {
      id: "q-gm-01",
      type: QuestionType.MultipleChoice,
      text: "Welcher Gegenstand ruiniert in Mario Kart gezielt den Erstplatzierten?",
      options: [
        { id: "A", label: "Der rote Panzer" },
        { id: "B", label: "Der Blitz" },
        { id: "C", label: "Der Stern" },
        { id: "D", label: "Der blaue Panzer" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-gm-02",
      type: QuestionType.MultipleChoice,
      text: "Was passierte in 'Die Sims', wenn man die Poolleiter entfernte?",
      options: [
        { id: "A", label: "Der Sim wurde unsichtbar" },
        { id: "B", label: "Der Sim konnte ertrinken" },
        { id: "C", label: "Das Spiel stürzte ab" },
        { id: "D", label: "Der Sim teleportierte sich" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-gm-03",
      type: QuestionType.MultipleChoice,
      text: "Was war der größte psychologische Terror beim Tamagotchi?",
      options: [
        { id: "A", label: "Es konnte nicht pausiert werden" },
        { id: "B", label: "Das Display war zu klein" },
        { id: "C", label: "Es konnte sterben, wenn man es vernachlässigte" },
        { id: "D", label: "Die Batterien waren nach zwei Tagen leer" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-gm-04",
      type: QuestionType.MultipleChoice,
      text: "Welches Spiel ist für den Satz 'Finish him!' bekannt?",
      options: [
        { id: "A", label: "Street Fighter" },
        { id: "B", label: "Tekken" },
        { id: "C", label: "Mortal Kombat" },
        { id: "D", label: "Soul Calibur" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-gm-05",
      type: QuestionType.MultipleChoice,
      text: "Welche Figur aus 'The Legend of Zelda' ist trotz der Verwirrung gar nicht Zelda?",
      options: [
        { id: "A", label: "Ganon" },
        { id: "B", label: "Impa" },
        { id: "C", label: "Link" },
        { id: "D", label: "Epona" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-gm-06",
      type: QuestionType.MultipleChoice,
      text: "Welches Pokémon entwickelt sich aus Kadabra, aber nur durch Tausch?",
      options: [
        { id: "A", label: "Mewtu" },
        { id: "B", label: "Abra" },
        { id: "C", label: "Simsala" },
        { id: "D", label: "Habitak" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-gm-07",
      type: QuestionType.MultipleChoice,
      text: "Welche Konsole war für das berüchtigte 'Rote Ringe des Todes'-Problem bekannt?",
      options: [
        { id: "A", label: "PlayStation 3" },
        { id: "B", label: "Xbox 360" },
        { id: "C", label: "Nintendo Wii" },
        { id: "D", label: "Sega Dreamcast" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-gm-08",
      type: QuestionType.MultipleChoice,
      text: "In welchem Spiel war 'rosebud' ein bekannter Geld-Cheat?",
      options: [
        { id: "A", label: "SimCity" },
        { id: "B", label: "Age of Empires" },
        { id: "C", label: "Die Sims" },
        { id: "D", label: "Rollercoaster Tycoon" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-gm-09",
      type: QuestionType.MultipleChoice,
      text: "Was war eine 'LAN-Party'?",
      options: [
        { id: "A", label: "Ein offizielles E-Sport-Turnier mit Preisgeld" },
        { id: "B", label: "Eine Spielemesse für Neuerscheinungen" },
        { id: "C", label: "Ein Treffen, bei dem alle eigene PCs mitbrachten und lokal zockten" },
        { id: "D", label: "Ein Online-Event für globale Multiplayer-Sessions" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-gm-10",
      type: QuestionType.MultipleChoice,
      text: "Wie heißt der blaue Panzer offiziell auf Deutsch laut Nintendo?",
      options: [
        { id: "A", label: "Stachi-Panzer" },
        { id: "B", label: "Blau-Panzer" },
        { id: "C", label: "Dorn-Panzer" },
        { id: "D", label: "Spitzen-Panzer" },
      ],
      correctOptionId: "A",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-gm-11",
      type: QuestionType.MultipleChoice,
      text: "Was bewirkte der GTA San Andreas Cheat-Code 'HESOYAM'?",
      options: [
        { id: "A", label: "Alle Waffen freischalten" },
        { id: "B", label: "Unbegrenzte Munition aktivieren" },
        { id: "C", label: "Volle Gesundheit, Rüstung und 250.000 Dollar" },
        { id: "D", label: "Fahndungslevel auf null setzen" },
      ],
      correctOptionId: "C",
      durationMs: 12_000,
      points: 3,
    },
    // Musik
    {
      id: "q-mu-01",
      type: QuestionType.MultipleChoice,
      text: "Welche Band machte 'Durch den Monsun' 2005 in Deutschland zum Hit?",
      options: [
        { id: "A", label: "Tokio Hotel" },
        { id: "B", label: "My Chemical Romance" },
        { id: "C", label: "Scooter" },
        { id: "D", label: "Silbermond" },
      ],
      correctOptionId: "A",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-mu-02",
      type: QuestionType.MultipleChoice,
      text: "Welche Band veröffentlichte 'Welcome to the Black Parade'?",
      options: [
        { id: "A", label: "Fall Out Boy" },
        { id: "B", label: "Panic! at the Disco" },
        { id: "C", label: "My Chemical Romance" },
        { id: "D", label: "Simple Plan" },
      ],
      correctOptionId: "C",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-mu-03",
      type: QuestionType.MultipleChoice,
      text: "Welches Originalstück hat Crazy Frog 2005 mit seiner Nervensäge-Version verewigt?",
      options: [
        { id: "A", label: "Blue (Da Ba Dee)" },
        { id: "B", label: "Axel F" },
        { id: "C", label: "Sandstorm" },
        { id: "D", label: "Popcorn" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-mu-04",
      type: QuestionType.MultipleChoice,
      text: "Wer hatte den 2000er-Hit 'Dragostea Din Tei' (aka Numa-Numa-Song)?",
      options: [
        { id: "A", label: "Eiffel 65" },
        { id: "B", label: "Basshunter" },
        { id: "C", label: "O-Zone" },
        { id: "D", label: "t.A.T.u." },
      ],
      correctOptionId: "C",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-mu-05",
      type: QuestionType.MultipleChoice,
      text: "Welche Gruppe ist für 'Blue (Da Ba Dee)' bekannt?",
      options: [
        { id: "A", label: "Aqua" },
        { id: "B", label: "Eiffel 65" },
        { id: "C", label: "Vengaboys" },
        { id: "D", label: "Cascada" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-mu-06",
      type: QuestionType.MultipleChoice,
      text: "Wie heißt der Sänger von Tokio Hotel?",
      options: [
        { id: "A", label: "Tom Kaulitz" },
        { id: "B", label: "Bill Kaulitz" },
        { id: "C", label: "Georg Listing" },
        { id: "D", label: "David Jost" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-mu-07",
      type: QuestionType.MultipleChoice,
      text: "Welche Boyband sang 'Bye Bye Bye'?",
      options: [
        { id: "A", label: "Backstreet Boys" },
        { id: "B", label: "Westlife" },
        { id: "C", label: "*NSYNC" },
        { id: "D", label: "Take That" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-mu-08",
      type: QuestionType.MultipleChoice,
      text: "Wie hieß 'Schnappi, das kleine ___'?",
      options: [
        { id: "A", label: "Nilpferd" },
        { id: "B", label: "Känguru" },
        { id: "C", label: "Krokodil" },
        { id: "D", label: "Dinosaurier" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-mu-09",
      type: QuestionType.MultipleChoice,
      text: "Welche Band veröffentlichte den Song 'In the End'?",
      options: [
        { id: "A", label: "Limp Bizkit" },
        { id: "B", label: "Papa Roach" },
        { id: "C", label: "System of a Down" },
        { id: "D", label: "Linkin Park" },
      ],
      correctOptionId: "D",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-mu-10",
      type: QuestionType.MultipleChoice,
      text: "Welche Sängerin wurde mit 'Complicated' zur Pop-Punk-Ikone der frühen 2000er?",
      options: [
        { id: "A", label: "Pink" },
        { id: "B", label: "Avril Lavigne" },
        { id: "C", label: "Kelly Clarkson" },
        { id: "D", label: "Alanis Morissette" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-mu-11",
      type: QuestionType.MultipleChoice,
      text: "Welcher Song war 1998 der erste Mainstream-Hit, der Autotune als Effekt einsetzte?",
      options: [
        { id: "A", label: "Cher – 'Believe'" },
        { id: "B", label: "T-Pain – 'Buy U a Drank'" },
        { id: "C", label: "Daft Punk – 'Harder Better Faster Stronger'" },
        { id: "D", label: "Eiffel 65 – 'Blue (Da Ba Dee)'" },
      ],
      correctOptionId: "A",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-mu-12",
      type: QuestionType.MultipleChoice,
      text: "Welcher Manager baute sowohl die Backstreet Boys als auch *NSYNC auf – und betrog beide?",
      options: [
        { id: "A", label: "Simon Fuller" },
        { id: "B", label: "Lou Pearlman" },
        { id: "C", label: "Irving Azoff" },
        { id: "D", label: "Clive Davis" },
      ],
      correctOptionId: "B",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-mu-13",
      type: QuestionType.MultipleChoice,
      text: "Wer war der Leadsänger von Linkin Park?",
      options: [
        { id: "A", label: "Chester Bennington" },
        { id: "B", label: "Mike Shinoda" },
        { id: "C", label: "Dave Grohl" },
        { id: "D", label: "Billy Joe Armstrong" },
      ],
      correctOptionId: "A",
      durationMs: 15_000,
      points: 2,
    },
    // Adulting Fails
    {
      id: "q-ad-01",
      type: QuestionType.MultipleChoice,
      text: "Was passiert typischerweise, wenn man rote und weiße Wäsche zusammen wäscht?",
      options: [
        { id: "A", label: "Gar nichts, ist ein Mythos" },
        { id: "B", label: "Die rote Farbe verblasst" },
        { id: "C", label: "Die Wäsche wird steif" },
        { id: "D", label: "Alles wird rosa – Verfärbungsrisiko" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-ad-02",
      type: QuestionType.MultipleChoice,
      text: "Was macht man mit einem Fettbrand auf dem Herd auf keinen Fall?",
      options: [
        { id: "A", label: "Deckel drauflegen" },
        { id: "B", label: "Mit Wasser löschen" },
        { id: "C", label: "Herd ausschalten" },
        { id: "D", label: "Feuerlöscher benutzen" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-ad-03",
      type: QuestionType.MultipleChoice,
      text: "Was bedeutet MHD auf Lebensmitteln?",
      options: [
        { id: "A", label: "Maximales Haltbarkeitsdatum" },
        { id: "B", label: "Mindesthaltbarkeitsdatum" },
        { id: "C", label: "Mittleres Haltbarkeitsdatum" },
        { id: "D", label: "Maximalhaltbarkeitsindex" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-ad-04",
      type: QuestionType.MultipleChoice,
      text: "Wofür steht ELSTER im deutschen Behördenkontext?",
      options: [
        { id: "A", label: "Eine Verordnung für Energiespargeräte" },
        { id: "B", label: "Das bundesweite Einwohnermelderegister online" },
        { id: "C", label: "Das elektronische Steuererklärungssystem der Finanzbehörden" },
        { id: "D", label: "Eine Naturschutz-Vogelschutzorganisation" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-ad-05",
      type: QuestionType.MultipleChoice,
      text: "Was ist der Sinn einer privaten Haftpflichtversicherung?",
      options: [
        { id: "A", label: "Schutz bei eigener Krankheit und Arbeitsausfall" },
        { id: "B", label: "Erstattung von gestohlenen eigenen Gegenständen" },
        { id: "C", label: "Absicherung gegen Schäden, die man anderen zufügt" },
        { id: "D", label: "Abdeckung von Mietschäden in der eigenen Wohnung" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-ad-06",
      type: QuestionType.MultipleChoice,
      text: "Wofür ist ein Pümpel (Gummisauger) da?",
      options: [
        { id: "A", label: "Zum Anbringen von Haken an Fliesen ohne Bohren" },
        { id: "B", label: "Zum Ausbeulen von Dellen in Türen oder Schränken" },
        { id: "C", label: "Zum Befüllen von Luftmatratzen ohne Pumpe" },
        { id: "D", label: "Zum Lösen von Verstopfungen in Toilette oder Abfluss" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    // Technik-Fails
    {
      id: "q-te-01",
      type: QuestionType.MultipleChoice,
      text: "Was war der große Nachteil eines Discman beim Gehen?",
      options: [
        { id: "A", label: "Er war zu schwer für Hosentaschen" },
        { id: "B", label: "Songs sprangen wegen Erschütterungen" },
        { id: "C", label: "Der Akku hielt nur 30 Minuten" },
        { id: "D", label: "Er spielte nur CD-Rs ab" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-te-02",
      type: QuestionType.MultipleChoice,
      text: "Was war T9 bei Handys?",
      options: [
        { id: "A", label: "Ein Betriebssystem für Nokia-Geräte" },
        { id: "B", label: "Eine Verschlüsselungstechnologie" },
        { id: "C", label: "Eine Texteingabehilfe zur Worterkennung auf Nummerntastaturen" },
        { id: "D", label: "Ein Messenger-Dienst" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-te-03",
      type: QuestionType.MultipleChoice,
      text: "Welche Marke steckt hinter dem Kult-Handy 3310?",
      options: [
        { id: "A", label: "Siemens" },
        { id: "B", label: "Ericsson" },
        { id: "C", label: "Motorola" },
        { id: "D", label: "Nokia" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-te-04",
      type: QuestionType.MultipleChoice,
      text: "Wofür war die Software 'Nero Burning ROM' bekannt?",
      options: [
        { id: "A", label: "Als kostenloser Medienplayer für MP3s" },
        { id: "B", label: "Als Brennsoftware für CDs und DVDs" },
        { id: "C", label: "Als Treibersoftware für Scanner und Drucker" },
        { id: "D", label: "Als Antivirenprogramm für Windows XP" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-te-05",
      type: QuestionType.MultipleChoice,
      text: "Welche Tauschbörse war neben Kazaa besonders berüchtigt für Viren und Fake-Dateien?",
      options: [
        { id: "A", label: "Napster" },
        { id: "B", label: "eMule" },
        { id: "C", label: "LimeWire" },
        { id: "D", label: "BitTorrent" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-te-06",
      type: QuestionType.MultipleChoice,
      text: "Welche Speicherkapazität hatte eine klassische 3,5-Zoll-Diskette?",
      options: [
        { id: "A", label: "700 MB" },
        { id: "B", label: "32 MB" },
        { id: "C", label: "256 KB" },
        { id: "D", label: "1,44 MB" },
      ],
      correctOptionId: "D",
      durationMs: 12_000,
      points: 3,
    },
    {
      id: "q-te-07",
      type: QuestionType.MultipleChoice,
      text: "Wofür war Winamp auf Windows bekannt?",
      options: [
        { id: "A", label: "Als kostenlose Videoschnittsoftware" },
        { id: "B", label: "Als Messenger-Dienst vor ICQ" },
        { id: "C", label: "Als populärer Medienplayer für MP3-Dateien" },
        { id: "D", label: "Als Brennsoftware für Audio-CDs" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-te-08",
      type: QuestionType.MultipleChoice,
      text: "Woran konnte man auf Kazaa erkennen, dass eine MP3-Datei gefälscht oder gefährlich war?",
      options: [
        { id: "A", label: "Die Datei hatte die Endung .exe statt .mp3" },
        { id: "B", label: "Der Dateiname war komplett in Großbuchstaben" },
        { id: "C", label: "Die Dateigröße war exakt 0 KB" },
        { id: "D", label: "Das Cover-Bild fehlte" },
      ],
      correctOptionId: "A",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-te-09",
      type: QuestionType.MultipleChoice,
      text: "Was passiert, wenn man einen starken Magneten an einen alten CRT-Monitor hält?",
      options: [
        { id: "A", label: "Der Monitor schaltet sich sofort aus" },
        { id: "B", label: "Das Bild verzerrt und verfärbt sich" },
        { id: "C", label: "Der Ton des Computers verstummt" },
        { id: "D", label: "Nichts – CRT sind magnetisch abgeschirmt" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    // Filme & Kino
    {
      id: "q-fi-01",
      type: QuestionType.MultipleChoice,
      text: "In welchem Film singt Céline Dion 'My Heart Will Go On'?",
      options: [
        { id: "A", label: "Dirty Dancing" },
        { id: "B", label: "Ghost" },
        { id: "C", label: "Titanic" },
        { id: "D", label: "Pretty Woman" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-fi-02",
      type: QuestionType.MultipleChoice,
      text: "Welcher Schauspieler spielte den Joker in 'The Dark Knight' (2008)?",
      options: [
        { id: "A", label: "Joaquin Phoenix" },
        { id: "B", label: "Jack Nicholson" },
        { id: "C", label: "Jared Leto" },
        { id: "D", label: "Heath Ledger" },
      ],
      correctOptionId: "D",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-fi-03",
      type: QuestionType.MultipleChoice,
      text: "Welcher Pixar-Film kam als erster in die Kinos?",
      options: [
        { id: "A", label: "A Bug's Life" },
        { id: "B", label: "Monsters, Inc." },
        { id: "C", label: "Toy Story" },
        { id: "D", label: "Findet Nemo" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-fi-04",
      type: QuestionType.MultipleChoice,
      text: "Aus welchem Film stammt der Satz 'Ich sehe tote Menschen'?",
      options: [
        { id: "A", label: "Der Exorzist" },
        { id: "B", label: "Ghostbusters" },
        { id: "C", label: "The Sixth Sense" },
        { id: "D", label: "The Others" },
      ],
      correctOptionId: "C",
      durationMs: 15_000,
      points: 2,
    },
    // Essen & Kultur
    {
      id: "q-es-01",
      type: QuestionType.MultipleChoice,
      text: "Welche Frucht wurde zum Symbol der Millennial-Küche?",
      options: [
        { id: "A", label: "Mango" },
        { id: "B", label: "Avocado" },
        { id: "C", label: "Papaya" },
        { id: "D", label: "Kiwi" },
      ],
      correctOptionId: "B",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-es-02",
      type: QuestionType.MultipleChoice,
      text: "Welcher Energy-Drink-Hersteller wirbt damit, dir 'Flügel zu verleihen'?",
      options: [
        { id: "A", label: "Monster" },
        { id: "B", label: "Burn" },
        { id: "C", label: "Rockstar" },
        { id: "D", label: "Red Bull" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-es-03",
      type: QuestionType.MultipleChoice,
      text: "Welcher TV-Koch wurde durch 'The Taste' und 'Kitchen Impossible' in Deutschland bekannt?",
      options: [
        { id: "A", label: "Alfons Schuhbeck" },
        { id: "B", label: "Tim Mälzer" },
        { id: "C", label: "Johann Lafer" },
        { id: "D", label: "Steffen Henssler" },
      ],
      correctOptionId: "B",
      durationMs: 15_000,
      points: 2,
    },
    // Mode & Beauty
    {
      id: "q-mo-01",
      type: QuestionType.MultipleChoice,
      text: "Welche Hosen-Variante saß in den frühen 2000ern so tief, dass die Unterwäsche zu sehen war?",
      options: [
        { id: "A", label: "Schlaghosen" },
        { id: "B", label: "High-Waist-Jeans" },
        { id: "C", label: "Baggy Pants" },
        { id: "D", label: "Low-Rise-Jeans" },
      ],
      correctOptionId: "D",
      durationMs: 20_000,
      points: 1,
    },
    {
      id: "q-mo-02",
      type: QuestionType.MultipleChoice,
      text: "Welche Farbe hatte das berühmte Livestrong-Silikonarmband von Lance Armstrong?",
      options: [
        { id: "A", label: "Rot" },
        { id: "B", label: "Blau" },
        { id: "C", label: "Grün" },
        { id: "D", label: "Gelb" },
      ],
      correctOptionId: "D",
      durationMs: 15_000,
      points: 2,
    },
    {
      id: "q-mo-03",
      type: QuestionType.MultipleChoice,
      text: "Welche Selfie-Pose wurde in den 2000ern zum absoluten Klischee?",
      options: [
        { id: "A", label: "Breites Lächeln" },
        { id: "B", label: "Augen verdrehen" },
        { id: "C", label: "Duckface (Schmollmund)" },
        { id: "D", label: "Daumen hoch" },
      ],
      correctOptionId: "C",
      durationMs: 20_000,
      points: 1,
    },
  ],
};

export function getDefaultQuiz(): Quiz {
  return MILLENNIALS_QUIZ;
}
