export const PROTOCOL_ERROR_CODES = {
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  ROOM_CLOSED: "ROOM_CLOSED",
  INVALID_JOIN_CODE: "INVALID_JOIN_CODE",
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  INVALID_STATE: "INVALID_STATE",
  NOT_AUTHORIZED: "NOT_AUTHORIZED",
  QUESTION_NOT_ACTIVE: "QUESTION_NOT_ACTIVE",
  ANSWER_ALREADY_SUBMITTED: "ANSWER_ALREADY_SUBMITTED",
  ANSWER_TOO_LATE: "ANSWER_TOO_LATE",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  PLAYER_NOT_FOUND: "PLAYER_NOT_FOUND",
} as const;

export const PROTOCOL_ERROR_CODE_VALUES = [
  PROTOCOL_ERROR_CODES.ROOM_NOT_FOUND,
  PROTOCOL_ERROR_CODES.ROOM_CLOSED,
  PROTOCOL_ERROR_CODES.INVALID_JOIN_CODE,
  PROTOCOL_ERROR_CODES.INVALID_PAYLOAD,
  PROTOCOL_ERROR_CODES.INVALID_STATE,
  PROTOCOL_ERROR_CODES.NOT_AUTHORIZED,
  PROTOCOL_ERROR_CODES.QUESTION_NOT_ACTIVE,
  PROTOCOL_ERROR_CODES.ANSWER_ALREADY_SUBMITTED,
  PROTOCOL_ERROR_CODES.ANSWER_TOO_LATE,
  PROTOCOL_ERROR_CODES.SESSION_NOT_FOUND,
  PROTOCOL_ERROR_CODES.PLAYER_NOT_FOUND,
] as const;

export type ProtocolErrorCode = (typeof PROTOCOL_ERROR_CODE_VALUES)[number];
