export const EVENTS = {
  CONNECTION_ACK: "connection:ack",
  CONNECTION_RESUME: "connection:resume",
  CONNECTION_RESUMED: "connection:resumed",
  ROOM_CREATE: "room:create",
  ROOM_CREATED: "room:created",
  ROOM_SETTINGS_UPDATE: "room:settings:update",
  ROOM_JOIN: "room:join",
  PLAYER_JOINED: "player:joined",
  LOBBY_UPDATE: "lobby:update",
  PLAYER_RECONNECTED: "player:reconnected",
  PLAYER_DISCONNECTED: "player:disconnected",
  GAME_START: "game:start",
  GAME_STARTED: "game:started",
  QUESTION_SHOW: "question:show",
  QUESTION_CONTROLLER: "question:controller",
  QUESTION_TIMER: "question:timer",
  ANSWER_SUBMIT: "answer:submit",
  ANSWER_ACCEPTED: "answer:accepted",
  ANSWER_REJECTED: "answer:rejected",
  ANSWER_PROGRESS: "answer:progress",
  QUESTION_CLOSE: "question:close",
  QUESTION_REVEAL: "question:reveal",
  SCORE_UPDATE: "score:update",
  NEXT_QUESTION_READY: "next-question:ready",
  NEXT_QUESTION_READY_PROGRESS: "next-question:ready-progress",
  GAME_NEXT_QUESTION: "game:next-question",
  GAME_FINISHED: "game:finished",
  ROOM_CLOSE: "room:close",
  ROOM_CLOSED: "room:closed",
  ERROR_PROTOCOL: "error:protocol",
} as const;

export type EventName = (typeof EVENTS)[keyof typeof EVENTS];

export const HOST_TO_SERVER_EVENT_NAMES = [
  EVENTS.CONNECTION_RESUME,
  EVENTS.ROOM_CREATE,
  EVENTS.ROOM_SETTINGS_UPDATE,
  EVENTS.GAME_START,
  EVENTS.GAME_NEXT_QUESTION,
  EVENTS.ROOM_CLOSE,
] as const;

export const PLAYER_TO_SERVER_EVENT_NAMES = [
  EVENTS.ROOM_JOIN,
  EVENTS.CONNECTION_RESUME,
  EVENTS.ANSWER_SUBMIT,
  EVENTS.NEXT_QUESTION_READY,
] as const;

export const CLIENT_TO_SERVER_EVENT_NAMES = [
  ...HOST_TO_SERVER_EVENT_NAMES,
  ...PLAYER_TO_SERVER_EVENT_NAMES,
] as const;

export const SERVER_TO_HOST_EVENT_NAMES = [
  EVENTS.CONNECTION_ACK,
  EVENTS.CONNECTION_RESUMED,
  EVENTS.ROOM_CREATED,
  EVENTS.LOBBY_UPDATE,
  EVENTS.PLAYER_RECONNECTED,
  EVENTS.PLAYER_DISCONNECTED,
  EVENTS.GAME_STARTED,
  EVENTS.QUESTION_SHOW,
  EVENTS.QUESTION_TIMER,
  EVENTS.ANSWER_PROGRESS,
  EVENTS.QUESTION_CLOSE,
  EVENTS.QUESTION_REVEAL,
  EVENTS.SCORE_UPDATE,
  EVENTS.NEXT_QUESTION_READY_PROGRESS,
  EVENTS.GAME_FINISHED,
  EVENTS.ROOM_CLOSED,
  EVENTS.ERROR_PROTOCOL,
] as const;

export const SERVER_TO_PLAYER_EVENT_NAMES = [
  EVENTS.CONNECTION_ACK,
  EVENTS.CONNECTION_RESUMED,
  EVENTS.PLAYER_JOINED,
  EVENTS.LOBBY_UPDATE,
  EVENTS.PLAYER_RECONNECTED,
  EVENTS.PLAYER_DISCONNECTED,
  EVENTS.GAME_STARTED,
  EVENTS.QUESTION_CONTROLLER,
  EVENTS.QUESTION_TIMER,
  EVENTS.ANSWER_ACCEPTED,
  EVENTS.ANSWER_REJECTED,
  EVENTS.QUESTION_CLOSE,
  EVENTS.QUESTION_REVEAL,
  EVENTS.SCORE_UPDATE,
  EVENTS.NEXT_QUESTION_READY_PROGRESS,
  EVENTS.GAME_FINISHED,
  EVENTS.ROOM_CLOSED,
  EVENTS.ERROR_PROTOCOL,
] as const;

export const SERVER_TO_CLIENT_EVENT_NAMES = [
  EVENTS.CONNECTION_ACK,
  EVENTS.CONNECTION_RESUMED,
  EVENTS.ROOM_CREATED,
  EVENTS.PLAYER_JOINED,
  EVENTS.LOBBY_UPDATE,
  EVENTS.PLAYER_RECONNECTED,
  EVENTS.PLAYER_DISCONNECTED,
  EVENTS.GAME_STARTED,
  EVENTS.QUESTION_SHOW,
  EVENTS.QUESTION_CONTROLLER,
  EVENTS.QUESTION_TIMER,
  EVENTS.ANSWER_ACCEPTED,
  EVENTS.ANSWER_REJECTED,
  EVENTS.ANSWER_PROGRESS,
  EVENTS.QUESTION_CLOSE,
  EVENTS.QUESTION_REVEAL,
  EVENTS.SCORE_UPDATE,
  EVENTS.NEXT_QUESTION_READY_PROGRESS,
  EVENTS.GAME_FINISHED,
  EVENTS.ROOM_CLOSED,
  EVENTS.ERROR_PROTOCOL,
] as const;

export type HostToServerEventName = (typeof HOST_TO_SERVER_EVENT_NAMES)[number];
export type PlayerToServerEventName = (typeof PLAYER_TO_SERVER_EVENT_NAMES)[number];
export type ClientToServerEventName = (typeof CLIENT_TO_SERVER_EVENT_NAMES)[number];
export type ServerToHostEventName = (typeof SERVER_TO_HOST_EVENT_NAMES)[number];
export type ServerToPlayerEventName = (typeof SERVER_TO_PLAYER_EVENT_NAMES)[number];
export type ServerToClientEventName = (typeof SERVER_TO_CLIENT_EVENT_NAMES)[number];
