export const EVENTS = {
  CONNECTION_ACK: "connection:ack",
  CONNECTION_RESUME: "connection:resume",
  CONNECTION_RESUMED: "connection:resumed",
  DISPLAY_CREATE_ROOM: "display:create-room",
  DISPLAY_ROOM_CREATED: "display:room-created",
  DISPLAY_HOST_PAIRED: "display:host-paired",
  HOST_CONNECT: "host:connect",
  HOST_CONNECTED: "host:connected",
  CATALOG_SUMMARY: "catalog:summary",
  ROOM_SETTINGS_UPDATE: "room:settings:update",
  ROOM_JOIN: "room:join",
  PLAYER_JOINED: "player:joined",
  LOBBY_UPDATE: "lobby:update",
  PLAYER_RECONNECTED: "player:reconnected",
  PLAYER_DISCONNECTED: "player:disconnected",
  GAME_START: "game:start",
  GAME_STARTED: "game:started",
  QUESTION_COUNTDOWN: "question:countdown",
  QUESTION_SHOW: "question:show",
  QUESTION_CONTROLLER: "question:controller",
  QUESTION_TIMER: "question:timer",
  ANSWER_SUBMIT: "answer:submit",
  ANSWER_ACCEPTED: "answer:accepted",
  ANSWER_REJECTED: "answer:rejected",
  ANSWER_PROGRESS: "answer:progress",
  QUESTION_CLOSE: "question:close",
  QUESTION_FORCE_CLOSE: "question:force-close",
  QUESTION_REVEAL: "question:reveal",
  SCORE_UPDATE: "score:update",
  NEXT_QUESTION_READY: "next-question:ready",
  NEXT_QUESTION_READY_PROGRESS: "next-question:ready-progress",
  GAME_NEXT_QUESTION: "game:next-question",
  GAME_SHOW_SCOREBOARD: "game:show-scoreboard",
  GAME_FINISH_NOW: "game:finish-now",
  GAME_FINISHED: "game:finished",
  PLAYER_REMOVE: "player:remove",
  ROOM_CLOSE: "room:close",
  ROOM_CLOSED: "room:closed",
  ERROR_PROTOCOL: "error:protocol",
} as const;

export type EventName = (typeof EVENTS)[keyof typeof EVENTS];

export const DISPLAY_TO_SERVER_EVENT_NAMES = [
  EVENTS.DISPLAY_CREATE_ROOM,
  EVENTS.CONNECTION_RESUME,
] as const;

export const HOST_TO_SERVER_EVENT_NAMES = [
  EVENTS.HOST_CONNECT,
  EVENTS.CONNECTION_RESUME,
  EVENTS.ROOM_SETTINGS_UPDATE,
  EVENTS.GAME_START,
  EVENTS.GAME_NEXT_QUESTION,
  EVENTS.QUESTION_FORCE_CLOSE,
  EVENTS.GAME_SHOW_SCOREBOARD,
  EVENTS.GAME_FINISH_NOW,
  EVENTS.PLAYER_REMOVE,
  EVENTS.ROOM_CLOSE,
] as const;

export const PLAYER_TO_SERVER_EVENT_NAMES = [
  EVENTS.ROOM_JOIN,
  EVENTS.CONNECTION_RESUME,
  EVENTS.ANSWER_SUBMIT,
  EVENTS.NEXT_QUESTION_READY,
] as const;

export const CLIENT_TO_SERVER_EVENT_NAMES = [
  ...DISPLAY_TO_SERVER_EVENT_NAMES,
  ...HOST_TO_SERVER_EVENT_NAMES,
  ...PLAYER_TO_SERVER_EVENT_NAMES,
] as const;

export const SERVER_TO_DISPLAY_EVENT_NAMES = [
  EVENTS.DISPLAY_ROOM_CREATED,
  EVENTS.DISPLAY_HOST_PAIRED,
  EVENTS.CONNECTION_ACK,
  EVENTS.CONNECTION_RESUMED,
  EVENTS.LOBBY_UPDATE,
  EVENTS.GAME_STARTED,
  EVENTS.QUESTION_COUNTDOWN,
  EVENTS.QUESTION_SHOW,
  EVENTS.QUESTION_TIMER,
  EVENTS.ANSWER_PROGRESS,
  EVENTS.QUESTION_CLOSE,
  EVENTS.QUESTION_REVEAL,
  EVENTS.SCORE_UPDATE,
  EVENTS.NEXT_QUESTION_READY_PROGRESS,
  EVENTS.GAME_FINISHED,
  EVENTS.ROOM_CLOSED,
  EVENTS.ERROR_PROTOCOL,
] as const;

export const SERVER_TO_HOST_EVENT_NAMES = [
  EVENTS.HOST_CONNECTED,
  EVENTS.CATALOG_SUMMARY,
  EVENTS.CONNECTION_ACK,
  EVENTS.CONNECTION_RESUMED,
  EVENTS.LOBBY_UPDATE,
  EVENTS.PLAYER_RECONNECTED,
  EVENTS.PLAYER_DISCONNECTED,
  EVENTS.GAME_STARTED,
  EVENTS.QUESTION_COUNTDOWN,
  EVENTS.QUESTION_SHOW,
  EVENTS.QUESTION_TIMER,
  EVENTS.ANSWER_PROGRESS,
  EVENTS.QUESTION_CLOSE,
  EVENTS.QUESTION_REVEAL,
  EVENTS.SCORE_UPDATE,
  EVENTS.NEXT_QUESTION_READY_PROGRESS,
  EVENTS.GAME_FINISHED,
  EVENTS.ROOM_CLOSED,
  EVENTS.ERROR_PROTOCOL,
] as const;

export const SERVER_TO_PLAYER_EVENT_NAMES = [
  EVENTS.CONNECTION_ACK,
  EVENTS.CONNECTION_RESUMED,
  EVENTS.PLAYER_JOINED,
  EVENTS.LOBBY_UPDATE,
  EVENTS.PLAYER_RECONNECTED,
  EVENTS.PLAYER_DISCONNECTED,
  EVENTS.GAME_STARTED,
  EVENTS.QUESTION_COUNTDOWN,
  EVENTS.QUESTION_CONTROLLER,
  EVENTS.QUESTION_TIMER,
  EVENTS.ANSWER_ACCEPTED,
  EVENTS.ANSWER_REJECTED,
  EVENTS.QUESTION_CLOSE,
  EVENTS.QUESTION_REVEAL,
  EVENTS.SCORE_UPDATE,
  EVENTS.NEXT_QUESTION_READY_PROGRESS,
  EVENTS.GAME_FINISHED,
  EVENTS.ROOM_CLOSED,
  EVENTS.ERROR_PROTOCOL,
] as const;

export const SERVER_TO_CLIENT_EVENT_NAMES = [
  EVENTS.DISPLAY_ROOM_CREATED,
  EVENTS.DISPLAY_HOST_PAIRED,
  EVENTS.HOST_CONNECTED,
  EVENTS.CATALOG_SUMMARY,
  EVENTS.CONNECTION_ACK,
  EVENTS.CONNECTION_RESUMED,
  EVENTS.PLAYER_JOINED,
  EVENTS.LOBBY_UPDATE,
  EVENTS.PLAYER_RECONNECTED,
  EVENTS.PLAYER_DISCONNECTED,
  EVENTS.GAME_STARTED,
  EVENTS.QUESTION_COUNTDOWN,
  EVENTS.QUESTION_SHOW,
  EVENTS.QUESTION_CONTROLLER,
  EVENTS.QUESTION_TIMER,
  EVENTS.ANSWER_ACCEPTED,
  EVENTS.ANSWER_REJECTED,
  EVENTS.ANSWER_PROGRESS,
  EVENTS.QUESTION_CLOSE,
  EVENTS.QUESTION_REVEAL,
  EVENTS.SCORE_UPDATE,
  EVENTS.NEXT_QUESTION_READY_PROGRESS,
  EVENTS.GAME_FINISHED,
  EVENTS.ROOM_CLOSED,
  EVENTS.ERROR_PROTOCOL,
] as const;

export type DisplayToServerEventName = (typeof DISPLAY_TO_SERVER_EVENT_NAMES)[number];
export type HostToServerEventName = (typeof HOST_TO_SERVER_EVENT_NAMES)[number];
export type PlayerToServerEventName = (typeof PLAYER_TO_SERVER_EVENT_NAMES)[number];
export type ClientToServerEventName = (typeof CLIENT_TO_SERVER_EVENT_NAMES)[number];
export type ServerToDisplayEventName = (typeof SERVER_TO_DISPLAY_EVENT_NAMES)[number];
export type ServerToHostEventName = (typeof SERVER_TO_HOST_EVENT_NAMES)[number];
export type ServerToPlayerEventName = (typeof SERVER_TO_PLAYER_EVENT_NAMES)[number];
export type ServerToClientEventName = (typeof SERVER_TO_CLIENT_EVENT_NAMES)[number];
